### ISSUE TITLE
COGA icon review suggestions

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#1008]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/coga/issues/231

**Comment by xfq** [comment]
> The check mark in East Asia means incorrect; the circle means correct.

I think "in East Asia" should be "in some countries, such as Japan and Korea", since the check mark means correct in China.

> tying a string around your finger

I don't think it's a well-known symbol worldwide. Although I have heard of it, I asked a few friends and they didn’t know...

**Comment by r12a** [comment]
In telecon:
Addison: are they using these icons as illustrations for this document only, or are the trying to create standardised icons for widespread use?

**Comment by himorin** [comment]
Agree with comment on icon 1.
For icon 7, I don't think string around a finger is global, such that ISO 3864 uses bandage around finger(s) for alerting on injury.

**Comment by r12a** [comment]
@himorin could you add your comments to https://github.com/w3c/coga/issues/231 ?

**Comment by himorin** [comment]
> @himorin could you add your comments to [w3c/coga#231](https://github.com/w3c/coga/issues/231) ?

Ah, yes. Right after I've submitted, I've noticed the issue was created (I should wait that...)

**Comment by xfq** [comment]
Should we add the `needs-resolution` label to this issue?
