### ISSUE TITLE
note about legacy encodings such as windows-1252 is invalid

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#101]
Raised by:Addison Phillips
Opened on:2015-10-15

http://www.w3.org/TR/2015/WD-findtext-20151015/#introduction

In the introduction we find this note:

> This specification defines the behavior for documents using a Unicode character encoding, such as UTF-8. Behavior for documents using legacy character encoding, such as windows-1252, may be anomolous. 

Since the document processing model for Web pages and other parts of the Open Web stack is based entirely on Unicode, the character encoding used to transmit or serialize a page being searched is not germane to finding text. 

How the document is converted to Unicode may matter: CharMod recommends that a "normalizing transcoder" be used. However, the specification is not about searching byte streams. It is about searching the converted Unicode character stream. There will be no anomalous search behavior unless something is very wrong with the APIs in this document. This note invites developers and implementers to question something that they really shouldn't be concerned about.

(editorial nit: anomalous is misspelled)

**Comment by aphillips** [comment]
obsolete
