### ISSUE TITLE
Better describe the likely outcomes of hyphenation (editorial)

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#1038]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/5973

**Comment by xfq** [comment]
CSSWG issue closed.

Changes: https://github.com/w3c/csswg-drafts/issues/5973#issuecomment-1366321015

**Comment by aphillips** [comment]
@r12a and @xfq Can you comment on the request in the CSS issue?

**Comment by r12a** [comment]
I added some additional requests after reviewing the latest spec text, and Florian made the appropriate edits.  So i believe we can close this tracker.

**Comment by aphillips** [comment]
Thanks. Done.
