### ISSUE TITLE
Non-US examples?

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1042]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/payment-request/issues/950

**Comment by marcoscaceres** [comment]
Agree, we should diversify these up a bit.

**Comment by marcoscaceres** [comment]
Sent pull request https://github.com/w3c/payment-request/pull/943

**Comment by r12a** [comment]
Reopened for i18n WG review.

**Comment by xfq** [comment]
WG issue closed. They added currencies other than the U.S. dollar.

New spec text: https://w3c.github.io/payment-request/#examples-of-usage

**Comment by marcoscaceres** [comment]
(apologies this was closed earlier... I didn't know I had magic powers to close issues across repos! 😲)

**Comment by aphillips** [comment]
Addressed.
