### ISSUE TITLE
Localizability of errors

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1046]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/payment-request/issues/951

**Comment by marcoscaceres** [comment]
We probably need to reopen https://github.com/w3c/payment-request/issues/327 and figure out what to do.

**Comment by r12a** [comment]
Closing until next version.
