### ISSUE TITLE
FindText API vs. Charmod-Norm

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#106]
Raised by:Addison Phillips
Opened on:2015-10-16

The FindText API specification appears to be doing a lot of what Charmod-Norm's section about text searching intends to do. This section is under-developed by comparison with FindText. 

By contrast, Charmod-Norm does have relatively well-developed sections defining case folding, character equivalence, Unicode normalization, and the like.

Would it make sense to reduce charmod's scope in favor of FindText for find operations?

**Comment by aphillips** [comment]
close as obsolete
