### ISSUE TITLE
list of displays: should it address display name, language, etc.?

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#113]
https://github.com/w3c/presentation-api/issues/315

Raised by:Addison Phillips
Opened on:2015-10-15

**Comment by aphillips** [comment]
https://github.com/w3c/presentation-api/issues/315

**Comment by r12a** [comment]
The spec has moved to [CR](https://lists.w3.org/Archives/Member/w3c-ac-members/2016JulSep/0009.html). Close ?

**Comment by r12a** [comment]
Closed as stale.
