### ISSUE TITLE
n/a

### ISSUE THREAD

**Issue by ntounsi** [w3c/i18n-activity#115]
comment moved to appropriate repo

**Comment by r12a** [comment]
Najib, please raise this issue against the actual article, not in this repo where the issues are meant to represent review comment pointers.  The url you need is 
https://github.com/w3c/i18n-drafts/issues/new?title=Feedback%20on%20questions/qa-css-lang&body=[source]%20%28http://www.w3.org/International/questions/qa-css-lang.en.php%29%20[en]%0A%0A

i will give you a short amount of time to copy the text above before deleting this comment.
