### ISSUE TITLE
make any element with an explicit lang attribute (and no dir attribute) bidi-isolated by default

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#118]
§ https://github.com/w3c/html/issues/226

**Comment by himorin** [comment]
almost no discussion on real state of spec in w3c/html issue, nor no action (incl. PR) was taken. 
[whatwg/html spec](https://html.spec.whatwg.org/multipage/dom.html#the-lang-and-xml:lang-attributes) does not state on this combination, we'd shift/post this discussion to whatwg/html.

**Comment by r12a** [comment]
I think we should just close this tracker issue. We still have a label attached to the HTML WG issue, so we'll see if there's further movement, but the original comment was pre-HTML5 and i think needs to be reframed in the context of the current situation.

It also seems to veer close to the idea of deriving directionality from language tags, which we recently looked into in detail and concluded was not a viable approach. (See https://github.com/w3c/string-meta/wiki/Base-direction-and-language-tags)

**Comment by r12a** [comment]
Agreed to close during telecon.
