### ISSUE TITLE
i18n-ISSUE-435: 3.2 scroll value and vertical writing

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#12]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=28268

https://www.w3.org/Bugs/Public/show_bug.cgi?id=24896
## 

Raised by:Richard Ishida
Opened on:2015-03-18

3.2 Text track regions, scroll value
http://www.w3.org/TR/2014/WD-webvtt1-20141111/#h3_text-track-regions

> Up
> Indicates that the cues in the region will be added at the bottom of the region and push any already displayed cues in the region up until all lines of the new cue are visible in the region.

If the text is set vertically, should the push be ltr/rtl, rather than up?

**Comment by silviapfeiffer** [comment]
Vertical scrolling has been moved to v2 of webvtt

**Comment by himorin** [comment]
this is https://github.com/w3c/webvtt/issues/316 and https://github.com/w3c/i18n-activity/issues/237

**Comment by r12a** [comment]
Closing as duplicate of https://github.com/w3c/i18n-activity/issues/237
