### ISSUE TITLE
Tighten up usages of "compatibilty caseless" comparisons used in the spec

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#121]
§ https://github.com/w3c/html/issues/216

previously
https://www.w3.org/Bugs/Public/show_bug.cgi?id=16970
## 

Raised by Addison.
Opened on 2012-05-07
Was Bug 16970 - i18n-ISSUE-105: compatibility caseless matching 

> 2.3 Case-sensitivity and string comparison
> http://www.w3.org/TR/html5/infrastructure.html#case-sensitivity-and-string-comparison
> 
> > Comparing two strings in a compatibility caseless manner means using the Unicode compatibility caseless match operation to compare the two strings.
> 
> a. The specific reference to compatibility caseless matching should be provided (D146 in chapter 3).
> b. I am unsure that compatibility caseless matching is desirable. It is only used twice in the whole document that I can find:
> 
> 2.5.9 (hashname reference value matching)
> 4.10.7.1.17 (radio button name attribute matching)
> 
> In both cases, name attributes defined in the document are being matched. I think that compatibility decomposition in the matching operation would be a surprise to users, who might expect, for example, these to be separate values: ①⑴⒈. More to the point, the Korean Hangul script has a complex relationship with compatibility decomposition.
> 
> I18N would suggest replacing compatibility caseless matching with canonical caseless matching.
> 
> c. It seems that this might be a stab at making 'name' attributes into 'identifiers', in which case compatibility decomposition is to be desired, with identifier caseless matching (which does use compatibility normalization but is slightly simpler).

**Comment by r12a** [comment]
this was closed in our tracker, but has new life in the html github issue

**Comment by aphillips** [comment]
This item needs our attention as a group. There is a long thread in the bugzilla bug and we weighed in several times.

HTMl51 still has this:

> Comparing two strings in a compatibility caseless manner means using the Unicode compatibility caseless match operation to compare the two strings, with no language-specific tailorings. [UNICODE]

This WG opposed this text previously and I believe it should still be removed or replaced.

**Comment by domenic** [comment]
This was fixed in https://github.com/whatwg/html/commit/6acdb2122298d2bb7bb839c0a61b4e1f9b0f9bc9, although implementations still have some work to do; see https://github.com/whatwg/html/pull/1941#issuecomment-255784034.

**Comment by r12a** [comment]
Doesn't appear to be fixed in w3c/html yet.

**Comment by himorin** [comment]
referred PR (and ticket) is one for #206, and situation should be the same (fixed in whatwg/html spec also).

**Comment by r12a** [comment]
Agreed to close during telecon as resolved.
