### ISSUE TITLE
i18n-ISSUE-97: Allowing a page to request a given locale (4.10.7.2 normativity) 

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#122]
https://github.com/w3c/html/issues/473

previously
https://www.w3.org/Bugs/Public/show_bug.cgi?id=16965

**Comment by r12a** [comment]
this issue was closed in our tracker, but we should check out Travis' latest comment

**Comment by aphillips** [comment]
So the bugzilla bug was closed as "already fixed" by Travis. He quoted this text:

> Browsers are encouraged to use user interfaces that present dates, times, and 
> numbers according to the conventions of either the locale implied by the input 
> element’s language or the user’s preferred locale. Using the page’s locale will 
> ensure consistency with page-provided data.

I'm not entirely cool with this text and think we should discuss it. My criticisms basically are:
1. I would prefer if the text weren't just "encouraging" but normative (the original issue). It doesn't have to say "MUST", but it ought to say "SHOULD", IMO.
2. The text lists dates, times, and numbers, but these should just be exemplery. Other things can be locale affected.
3. There is a missing step linking language and locale.
4. This allows both page provided locale (@lang) _or_ the user's locale.

I would suggest that this text be altered thusly:

> Browsers SHOULD provide user interfaces that present locale-affected formats such as dates, times, and numbers according to the conventions of the locale derived from the input element’s language attribute. Using the page’s locale will ensure consistency with page-provided data.

**Comment by aphillips** [comment]
See https://github.com/w3c/html/issues/473

**Comment by aphillips** [comment]
change in html/#473 looks good to me.
