### ISSUE TITLE
i18n-ISSUE-89: Time zones and local dates and times

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#123]
https://github.com/w3c/html/issues/474

previously https://www.w3.org/Bugs/Public/show_bug.cgi?id=16960

**Comment by r12a** [comment]
this issue was closed in our tracker, but Travis added some additional info before closing the bug

**Comment by aphillips** [comment]
Created https://github.com/w3c/html/issues/474

**Comment by r12a** [comment]
Addison's wording added to the spec. Close?

**Comment by aphillips** [comment]
concur with closing
