### ISSUE TITLE
Default styling for q element

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#124]
§ https://github.com/w3c/html/issues/314

previously
https://www.w3.org/Bugs/Public/show_bug.cgi?id=13398
https://www.w3.org/Bugs/Public/show_bug.cgi?id=13417

**Comment by himorin** [comment]
PR (https://github.com/w3c/html/pull/1228) closing the target issue (https://github.com/w3c/html/issues/314) is not applied to [whatwg/html 14.3.6 Quotes](https://html.spec.whatwg.org/multipage/rendering.html#quotes).

**Comment by xfq** [comment]
I propose that we close this, because we have #571 to track the corresponding WHATWG issue.

**Comment by r12a** [comment]
I also think we can close this, since https://github.com/w3c/i18n-activity/issues/571 already takes up the same request with WhatWG spec.

**Comment by r12a** [comment]
Agreed to close in favour of #571.
