### ISSUE TITLE
Sort out issues with [inputmode]

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#126]
§ https://github.com/w3c/html/issues/269

**Comment by himorin** [comment]
refine was performed at [whatwg/html](https://html.spec.whatwg.org/multipage/interaction.html#input-modalities:-the-inputmode-attribute) by issue https://github.com/whatwg/html/issues/3077 and PR https://github.com/whatwg/html/pull/3260 to address (most of) discussions in https://github.com/w3c/html/issues/269 .
propose close?, and I think no other action is required.
