### ISSUE TITLE
i18n-ISSUE-436: 6.2.1 line heights

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#13]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=28269
## 

Raised by:Richard Ishida
Opened on:2015-03-18

6.2.1 Processing model
http://www.w3.org/TR/2014/WD-webvtt1-20141111/#h4_processing-model

"Let lineHeight be '5.33vh' ('vh' is a CSS unit) [CSSVALUES] and regionHeight be the text track region lines."

It wasn't clear whether this sets the line-height for cue content to be a fixed height, or whether it's possible to adapt that height for scripts such as Tibetan, Thai or Arabic, which require far more vertical line height than, say, Latin text.

**Comment by r12a** [comment]
Seems to not be an issue, since you can apply via CSS.
Suggest we close.
Richard Ishida, 24 Mar 2015, 13:46:09

**Comment by aphillips** [comment]
The question isn't whether you can style you way out of this but rather whether the default should be hardcoded in the spec vs. (for example) being computed from the content. However, I concur that this is not worth pursuing.
