### ISSUE TITLE
 Add section on internationalization #53 

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#131]
§ https://github.com/w3c/payment-request/issues/53
## 

> Migrating from w3c/webpayments#84:
> 
> The spec needs to clearly state how it will handle internationalization issues (such as selection order for language via explicit preferences, Accept-Language headers, etc.)

**Comment by marcoscaceres** [comment]
IIRC, @aphillips prefers we don't call out internationalization in a section, but instead make sure we instead address internationalization throughout the spec (which I agree with).

**Comment by ianbjacobs** [comment]
Please see note from @marcoscaceres and close here.
