### ISSUE TITLE
payment shipping option label not localizable

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1357]
PaymentShippingOption dictionary 
https://www.w3.org/TR/2020/CR-payment-request-20201203/#paymentshippingoption-dictionary

> >  label member
>    A human-readable string description of the item. The user agent SHOULD use this string to display the shipping option to the user. 

The `label` member has no language or direction metadata. Further, it cannot be localized by providing reference to a multilingual construct of some sort. There doesn't appear to be a language negotiation mechanism so that a language can be requested.

The SHOULD might be problematic vs. allowing the user agent to wrap the provided display string with a localized value, i.e. it could say something approximately like:

> The user agent SHOULD use this string (or a localized version available to the user agent locally) to display the shipping option to the user.

---
Instructions: 

This follows the process at https://w3c.github.io/i18n-activity/guidelines/review-instructions.html

1. **CREATE A PROPOSED REVIEW COMMENT BY REPLACING THE PROMPTS ABOVE THIS PARAGRAPH, BUT LEAVE THIS PARAGRAPH INTACT AS WELL AS THE TEXT BELOW IT** Then ask the i18n WG to review your comment.

2. Set a label to identify the spec. This starts with s: followed by the spec's short name. If you are unable to do that, ask a W3C staffer to help.

3. After discussion with the i18n WG, raise this issue to the WG that owns the spec. Use the text above this para as the basis for that comment.

4. Replace the text 'link_to_issue_raised' below with a link to the place you raised the issue. Do NOT remove the initial '§ '.

5. Edit this issue to remove this paragraph and ALL THE TEXT ABOVE IT.

6. Remove the 'pending' label.

**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ link_to_issue_raised

**Comment by marcoscaceres** [comment]
Can probably be addressed by revisiting https://github.com/w3c/payment-request/issues/327

**Comment by r12a** [comment]
This was raised in a different issue, so closing.
