### ISSUE TITLE
Payer error dictionary not localizable

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1359]
14.1.2 PayerErrors dictionary 
https://www.w3.org/TR/2020/CR-payment-request-20201203/#payererrors-dictionary

```
 const payer = {
  email: "The domain is invalid.",
  phone: "Unknown country code.",
  name: "Not in database.",
};
```

Example 13 shows the payer errors dictionary being used to convey unlabeled natural language string values. As noted in other comments, there is no language negotiation scheme in place. There is also no metadata here to help with display.

---
Instructions: 

This follows the process at https://w3c.github.io/i18n-activity/guidelines/review-instructions.html

1. **CREATE A PROPOSED REVIEW COMMENT BY REPLACING THE PROMPTS ABOVE THIS PARAGRAPH, BUT LEAVE THIS PARAGRAPH INTACT AS WELL AS THE TEXT BELOW IT** Then ask the i18n WG to review your comment.

2. Set a label to identify the spec. This starts with s: followed by the spec's short name. If you are unable to do that, ask a W3C staffer to help.

3. After discussion with the i18n WG, raise this issue to the WG that owns the spec. Use the text above this para as the basis for that comment.

4. Replace the text 'link_to_issue_raised' below with a link to the place you raised the issue. Do NOT remove the initial '§ '.

5. Edit this issue to remove this paragraph and ALL THE TEXT ABOVE IT.

6. Remove the 'pending' label.

**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ link_to_issue_raised

**Comment by marcoscaceres** [comment]
Can probably be addressed by revisiting https://github.com/w3c/payment-request/issues/327

**Comment by aphillips** [comment]
Forgot to remove pending label previously. This issue is merged into the issue 948 that I filed against payment-request.
