### ISSUE TITLE
[Editorial] U+ notation is incorrect

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1394]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/webauthn/issues/1641

**Comment by xfq** [comment]
WG issue closed. Changes: https://github.com/w3c/webauthn/pull/2165/files

**Comment by aphillips** [comment]
fixed
