### ISSUE TITLE
Example structure 'total' not localizable?

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1412]
Example 2 under 1.2.2. Authentication
https://w3c.github.io/secure-payment-confirmation/#sctn-sample-authentication

```
    total: {
      label: "Total",
      amount: {
        currency: "USD",
        value: "5.00",
      },
    },
```

The string `label` contains natural language text without language/direction information. While it is probably beyond the scope of SCP to discuss how localization or language negotiation takes place within a given bit of JS, it's probably a good idea to show examples that follow best practices.

---
Instructions: 

This follows the process at https://w3c.github.io/i18n-activity/guidelines/review-instructions.html

1. **CREATE A PROPOSED REVIEW COMMENT BY REPLACING THE PROMPTS ABOVE THIS PARAGRAPH, BUT LEAVE THIS PARAGRAPH INTACT AS WELL AS THE TEXT BELOW IT** Then ask the i18n WG to review your comment.

2. Set a label to identify the spec. This starts with s: followed by the spec's short name. If you are unable to do that, ask a W3C staffer to help.

3. After discussion with the i18n WG, raise this issue to the WG that owns the spec. Use the text above this para as the basis for that comment.

4. Replace the text 'link_to_issue_raised' below with a link to the place you raised the issue. Do NOT remove the initial '§ '.

5. Edit this issue to remove this paragraph and ALL THE TEXT ABOVE IT.

6. Remove the 'pending' label.

**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ link_to_issue_raised

**Comment by xfq** [comment]
nit: "SCP" -> "SPC"

**Comment by himorin** [comment]
This dictionary is defined as [PaymentItem in Payments Request spec](https://w3c.github.io/payment-request/#dom-paymentitem).

**Comment by aphillips** [comment]
Closing as rejected. This issue might be dealt with when we resolve language negotiation and handling of natural language text. For now it is not actionable by SPC.
