### ISSUE TITLE
Use of heuristic for direction instead of metadata

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1465]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/wot-thing-description/issues/1416

**Comment by r12a** [comment]
There's also the article [Can we derive base direction from language?](https://www.w3.org/International/questions/qa-direction-from-language)

**Comment by aphillips** [comment]
fixed
