### ISSUE TITLE
Use of BCP47 term "well-formed" without definition

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1466]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/wot-thing-description/issues/1415

**Comment by xfq** [comment]
WG issue closed. They replaced 'well-formed language tag' with 'valid language tag' and links to the ED version of the Glossary.

Current spec text: https://w3c.github.io/wot-thing-description/#titles-descriptions-serialization-json
