### ISSUE TITLE
No base direction metadata

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1467]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/wot-thing-description/issues/1414

**Comment by xfq** [comment]
WG issue closed.

Current spec text: https://w3c.github.io/wot-thing-description/#titles-descriptions-serialization-json
