### ISSUE TITLE
Emphasize locale-neutrality in enum examples

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1470]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/wot-thing-description/issues/1411

**Comment by xfq** [comment]
WG issue closed.

Changes: https://github.com/w3c/wot-thing-description/pull/1448/files

**Comment by aphillips** [comment]
fixed
