### ISSUE TITLE
Don't provide a language parameter for word-boundary-detection

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#1472]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/7193

**Comment by aphillips** [comment]
@r12a Did you mean to file this (and other) pending issues against a spec? (CSS Text 4 in this case)

**Comment by fantasai** [comment]
I think the idea of this parameter was that it enables word-boundary-detection for the specified language(s) only; other languages are not affected. What language the element is actually in is what determines the language used for the word-boundary-detection. For example, if I have a trilingual document in English, Japanese, and French, if I set `word-boundary-detection: auto(ja)` then it will enable detection for Japanese paragraphs only. If there are no Japanese paragraphs, it won't have any effect.

**Comment by fantasai** [comment]
It should probably allow a list of values, though.

**Comment by aphillips** [comment]
fixed
