### ISSUE TITLE
Example 5 choice of language

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1494]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/7131

**Comment by xfq** [comment]
CSSWG issue closed. Changes: https://github.com/w3c/csswg-drafts/commit/a9e2d09f7e41f07535f161920d07ce94e2fb6dab
