### ISSUE TITLE
Question: is `id` in 7.2.2.1.1 the same as TD `id`?

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1524]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/wot-discovery/issues/320

**Comment by mmccool** [comment]
Yes, they are the same.  If the TD has no id (it is anonymous) than one is generated.  To address the concern you raised (if ids are URL and we use them in a path there may be special character conflicts) we have added assertions to
- Indicate that URL-encoding must be used to escape special characters allowing the id to be embedded in a path
- Indicate that when ids are generated for anonymous TDs, UUIDv4 should be used.

**Comment by aphillips** [comment]
@mmccool Please put comments on the wot-discovery issue rather than in our repo. I copied the above for you and replied. Thanks!!

**Comment by aphillips** [comment]
resolved
