### ISSUE TITLE
UTF-8 encoding of value should be more clearly defined.

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1527]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/baggage/issues/100

**Comment by xfq** [comment]
WG issue closed.

Current text: https://www.w3.org/TR/baggage/#value

**Comment by aphillips** [comment]
fixed
