### ISSUE TITLE
Limiting the length of strings

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-activity#1549]
**This is a tracker issue.** Only discuss things here if they are i18n group internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/wot-thing-description/issues/1516

**Comment by xfq** [comment]
WG issue closed.

They mentioned that the length of a string (i.e., `minLength` and `maxLength`) is defined as the number of its characters as defined by [[RFC8259](https://w3c.github.io/wot-thing-description/#bib-rfc8259)].

It doesn't look like it's clearly stated in RFC 8259 what the units of characters are either.

**Comment by aphillips** [comment]
I added a comment to the above issue asking for them to reopen it. The authors of RFC8259 clearly know the difference between code units and code points but they don't define 'length' anywhere. This spec should take responsibility for saying which they mean.
