### ISSUE TITLE
Should navigator.language and and/or HTTP Accept-Language include locale?

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#156]
https://www.w3.org/Mail/flatten/index?subject=Should+navigator.language+and+and%2For+HTTP+Accept-Language+include+locale%3F&list=public-whatwg-archive

This was brought to my attention by Mike Smith.

**Comment by KatyMawhood** [comment]
I would propose that: 

(1) Discuss proposal for navigator.locales (https://github.com/whatwg/html/issues/171).
(2) There are not clear changes to be made to the HTTP Accept-Language. Therefore, unless there are any further objections, I propose that we close this issue.

**Comment by r12a** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2019/03/21-i18n-minutes.html#item08).

- `RESOLVED: ] close`
<details><summary><i class="differentiate">View the transcript</i></summary>
<a href="https://github.com/w3c/i18n-activity/issues/156">https://github.com/w3c/i18n-activity/issues/156</a><br/>
&lt;Katy> <a href="https://github.com/w3c/i18n-activity/issues/156">https://github.com/w3c/i18n-activity/issues/156</a><br/>
<b>david:</b> introducing more metadata into navigator locale<br/>
... can put in full locales in A-L<br/>
... stuff like currency formats<br/>
<b>[RESOLVED:</b>] close<br/>
</details>
