### ISSUE TITLE
Error message in unspecified language

### ISSUE THREAD

**Issue by bert-github** [w3c/i18n-activity#1565]
2.6 LifecycleError interface
https://www.w3.org/TR/miniapp-lifecycle/#lifecycleerror-interface

> [Exposed=Window]
> interface LifecycleError {
>     readonly attribute DOMString errorDescription;
> };
[…]
> The errorDescription attribute is a developer-friendly textual description of the error global application lifecycle states.

An application can register a callback function (see [section2.4](https://www.w3.org/TR/miniapp-lifecycle/#miniapp-global-application-lifecycle-interface-and-callbacks)) that is to be called when a ‘script error’ occurs. That function will get as parameter an object of type LifecycleError (quoted above), which contains just one thing: an errorDescription string. Presumably, the OS or some runtime environment creates that string when it detects an error and calls the application's callback function with it.

It is not specified in what language and writing direction that string will be. And neither are the possible values of the string defined by this specification (which would allow an application to treat them as identifiers and translate them).

It is not clear if there can in fact be multiple types of errors and thus if that string is needed to distinguish between the different types; or, otherwise, if there is only one kind of error (‘script error’) and the error description can thus be ignored, because it contains no additional information.

---
**WHEN CREATING A NEW ISSUE DO SO ABOVE THIS PARAGRAPH, REPLACING THE PROMPTS, BUT LEAVE THIS PARAGRAPH INTACT AS WELL AS THE TEXT BELOW IT** When this issue is raised in the github/bugzilla/mail of the WG that owns the spec, use the text above this para as the basis for that comment. Then edit this issue to remove this paragraph and ALL THE TEXT ABOVE IT. Replace the text 'link_to_issue_raised' below with a link to the place you raised the issue, but leave the remaining text below this para unaltered.

**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ link_to_issue_raised

**Comment by aphillips** [comment]
dupes 1535
