### ISSUE TITLE
Define or remove the use of the term Plain Unicode String

### ISSUE THREAD

**Issue by stevenatkin** [w3c/i18n-activity#157]
§ https://github.com/whatwg/html/issues/4798

Was formerly raised against the W3C HTML spec at:
https://github.com/w3c/html/issues/476

**Comment by himorin** [comment]
update (https://github.com/w3c/html/commit/fc60cc441fc1e9a3d149e37ecc42dadcb1c37a36) for w3c/html which closes target issue is not included in [whatwg/html 6.7.2](https://html.spec.whatwg.org/multipage/dnd.html#the-drag-data-store). And a comment was added to that update that just adding "Values must not be escaped." to the state is enough or not.

**Comment by r12a** [comment]
It seems to me that we could open an issue for whatwg along the following lines:

Is 'Plain Unicode string' defined somewhere?  Is the meaning just 'a plain text Unicode string' (ie. a sequence of Unicode code points)?  Is it acceptable to include escaped characters, and if so, how?

**Comment by aphillips** [comment]
Item appears to be resolved in whatwg

**Comment by himorin** [comment]
PR https://github.com/whatwg/html/pull/4827 merged to rename `Plain Unicode String` to `text`.

**Comment by r12a** [comment]
Agreed to close during telecon.
