### ISSUE TITLE
Clarify DOMString comparison method in dictionaly WebTransportHash (of WebTransport spec)

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#1570]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/webtransport/issues/413

**Comment by himorin** [comment]
text updated by PR (merged) as we suggested. propose to close this tracker.
https://github.com/w3c/webtransport/pull/453/files

**Comment by aphillips** [comment]
fixed
