### ISSUE TITLE
Human readable error message without language info

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#1571]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/webtransport/issues/414

**Comment by himorin** [comment]
should add a link to similar issue, like https://github.com/w3c/i18n-activity/issues/79, and string-meta, also current work with like TC39.

**Comment by himorin** [comment]
propose to close, An note with phrase `First-strong heuristics can be used for direction when displaying the value.`  is added via https://github.com/w3c/webtransport/pull/513

**Comment by aphillips** [comment]
we indicated that we were satisfied
