### ISSUE TITLE
Term "monkey-patch" may not be inclusive?

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1582]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/secure-payment-confirmation/issues/207

**Comment by stephenmcgruer** [comment]
Fixed in https://github.com/w3c/secure-payment-confirmation/commit/50f0e7ccecd5a23b650cea3dc5e9f3219e6c69a7

**Comment by ianbjacobs** [comment]
Now deployed:
 https://www.w3.org/TR/2022/WD-secure-payment-confirmation-20220908/

**Comment by aphillips** [comment]
fixed; also not i18n
