### ISSUE TITLE
`DOMString` for `payeeName` vs. `USVString` for `payeeOrigin`

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1583]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/secure-payment-confirmation/issues/208

**Comment by xfq** [comment]
WG issue closed. `payeeName` and `displayName` are now `USVString`s. I propose that we close this tracker issue.

**Comment by aphillips** [comment]
fixed; 2023-04-27
