### ISSUE TITLE
Use of modifier keys for accesskey

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#159]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/html/issues/1012

**Comment by r12a** [comment]
See this PR https://github.com/w3c/html/pull/1159#pullrequestreview-92480374

Is this a satisfactory resolution?

**Comment by himorin** [comment]
Target of this tracker was fixed in w3c/html by the same PR as #481, and current situation should be the same.

**Comment by r12a** [comment]
I propose we close this tracker (issue already closed) and refer instead to issues being prepared for the WhatWG spec.

**Comment by r12a** [comment]
Agreed to close during telecon.
