### ISSUE TITLE
specification of lowercase is incomplete

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1598]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/trace-context/issues/506

**Comment by xfq** [comment]
IMHO it would be useful to link to the relevant Infra term.

Related terms include:

* [byte-lowercase](https://infra.spec.whatwg.org/#byte-lowercase)
* [ASCII lower alpha](https://infra.spec.whatwg.org/#ascii-lower-alpha)
* [ASCII lowercase](https://infra.spec.whatwg.org/#ascii-lowercase)

**Comment by xfq** [comment]
WG issue closed. Updated spec text:

* https://w3c.github.io/trace-context/#header-name
* https://w3c.github.io/trace-context/#header-name-0
