### ISSUE TITLE
Change how invalid lang codes are to be treated by user agents

### ISSUE THREAD

**Issue by stevenatkin** [w3c/i18n-activity#160]
3.2.5.3 The lang and xml:lang attributes
http://www.w3.org/TR/html51/single-page.html#the-lang-and-xmllang-attributes

The specification states that invalid BCP47 language codes are to be passed to user agents, but then restricts how the invalid code is to be treated by the user agent. The spec states that if the user agent understands the invalid code and wants to interpret that as synonym for another language code then that would be incorrect. I think we should remove this restriction and simply pass the invalid code to the user agent and then allow the user agent to interpret that code any way they wish.

**Comment by r12a** [comment]
During telecon decided that this is ok, since it protects the browser from having to recognise ill-formed subtags as BCP47, with possible threat after to the standard.
