### ISSUE TITLE
iTXt language tag description needs attention

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1609]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/PNG-spec/issues/241

**Comment by r12a** [comment]
So that you have an example of a 3-letter language subtag, why not include cmn?

**Comment by aphillips** [comment]
done.
