### ISSUE TITLE
Question about the use of Content-Language as fallback language for lang attribute.

### ISSUE THREAD

**Issue by stevenatkin** [w3c/i18n-activity#161]
3.2.5.3 The lang and xml:lang attributes
http://www.w3.org/TR/html51/single-page.html#the-lang-and-xmllang-attributes

I am not sure if we really want to use the value of Content-Language as a fallback for setting the lang attribute. My understanding is that the Content-Language value indicates the language of the intended audience of a page, rather than the language of a specific range of text which in this case would be all elements of the page. Additionally, the HTML5.1 spec states that if there are multiple values for Content-Language then the language of the page is to be set to unknown. Given all of this I am not sure if we should be using Content-Language as a fallback for determining the language of the page in the event the lang attribute is not specified.

**Comment by r12a** [comment]
We agree that this is not an ideal situation, but the current text is the result of a previous round of discussion and not new text.
