### ISSUE TITLE
Prefer 3339 to RFC1123/RFC822 date-time?

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1618]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/PNG-spec/issues/240

**Comment by xfq** [comment]
WG issue closed. The spec now prefers RFC 3339.

Changes: https://github.com/w3c/PNG-spec/pull/289/files
