### ISSUE TITLE
Unicode terminology

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-activity#1628]
**This is a tracker issue.** Only discuss things here if they are i18n group internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/uievents-code/issues/36

**Comment by deepgithubforever** [comment]
> **This is a tracker issue.** Only discuss things here if they are i18n group internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**
> 
> § https://github.com/w3c/uievents-code/issues/36
>

**Comment by xfq** [comment]
WG issue closed. Current spec text: https://w3c.github.io/uievents-code/#style-conventions
