### ISSUE TITLE
Line breaking opportunities at the boundary of a white-space:pre inline element #189

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#165]
§ https://github.com/w3c/csswg-drafts/issues/189

**Comment by xfq** [comment]
CSSWG issue closed. Should we close this?

(Note that it's `i18n-needs-resolution` in the CSSWG issue, but `tracker` in the tracker issue, and we should change one of them to match the other.)

**Comment by r12a** [comment]
The fix seems non-controversial, so i second the proposal to close.
