### ISSUE TITLE
"in a language displayed top to bottom" -> "in vertically set text"

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#1650]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/wcag/issues/2996

**Comment by xfq** [comment]
Added the `needs-resolution` label.

**Comment by r12a** [comment]
The WG made the recommended change. I think we should close this.
