### ISSUE TITLE
Use of uppercase hex for code points (editorial)

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1652]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/uievents-key/issues/60

**Comment by hober** [comment]
See also https://infra.spec.whatwg.org/#code-points

**Comment by plehegar** [comment]
@xfq  This issue has been resolved by WebApps and ought to be closed.

**Comment by xfq** [comment]
Agreed. Given that it's a simple editorial comment, I'll go ahead and close this issue.

Feel free to reopen if there's any objection.
