### ISSUE TITLE
 Support css-counter-styles-3

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#170]
Bugs have been created asking 3 major browsers to implement customisable counter styles per the [CSS Counter Styles](https://www.w3.org/TR/css-counter-styles-3/) spec, which is in CR. (Firefox already has support.)

Blink: 
https://bugs.chromium.org/p/chromium/issues/detail?id=687225  ETA M91
(duplicate: https://bugs.chromium.org/p/chromium/issues/detail?id=625771#c5)

Webkit:
https://bugs.webkit.org/show_bug.cgi?id=167645
https://bugs.webkit.org/show_bug.cgi?id=223150

Obsolete, Edge: 
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10809826/

**Comment by xfq** [comment]
In https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10809826/ :

> Feature requests should go to our uservoice. We only track bugs here.

So I posted a feature request here: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/32403796-support-for-counter-style

Hope that helps.

**Comment by r12a** [comment]
Thanks @xfq .

**Comment by r12a** [comment]
The 3 major browser engines now support customised counter styles.
