### ISSUE TITLE
Reference to BIDI should probably be UAX9

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1704]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/manifest/issues/1081

**Comment by christianliebel** [comment]
This can probably be closed after the changes introduced by https://github.com/w3c/manifest/pull/1131.

**Comment by xfq** [comment]
See also https://github.com/w3c/manifest/pull/1135/files

**Comment by aphillips** [comment]
Fixed.
