### ISSUE TITLE
Remove the Internationalization section

### ISSUE THREAD

**Issue by bert-github** [w3c/i18n-activity#1780]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/vc-jose-cose/issues/172

**Comment by aphillips** [comment]
This issue was approved in the 2023-10-19 teleconference.

**Comment by aphillips** [comment]
Fixed
