### ISSUE TITLE
no need to refer considerations on data serialization defined in the core?

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#1786]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/vc-json-schema/issues/222

**Comment by aphillips** [comment]
Fixed labels and matched the title of this issue to the one in their repo.

**Comment by aphillips** [comment]
This issue was addressed
