### ISSUE TITLE
Clarify note on single character of mi as italic

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#1834]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/mathml-core/issues/231

**Comment by bert-github** [comment]
‘containing a single letter’ could be ambiguous, in the sense that <code>&lt;mi&gt;a9&lt;/mi&gt;</code> contains a single letter (the other character is a not a letter). On the other hand, this text in 3.2.2 is just an example. The normative text in 4.2 uses ‘character’ (as you quoted).

As for using ‘identifiers’, I'm not sure, but maybe it should be explained somewhere that spaces are ignored: <code>&lt;mi&gt; a &lt;/mi&gt;</code> contains one character, the spaces don't count. The MathML3 spec defines that (in [2.1.7 Collapsing Whitespace in Input](https://www.w3.org/TR/MathML/chapter2.html#fund.collapse)) and MathML Core is a subset of MathML3, but a note or an example to remind readers of that fact might be useful.

**Comment by aphillips** [comment]
fixed
