### ISSUE TITLE
Should there be a Best Practice to use Unicode and/or UTF-8?

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#185]
https://www.w3.org/Mail/flatten/index?subject=%5Bi18n+review+comment%5D+Should+there+be+a+Best+Practice+to+use+Unicode&list=public-dwbp-comments

**Comment by xfq** [comment]
The Data on the Web Best Practices Working Group has been closed. Should we close this issue?

**Comment by r12a** [comment]
The document is a Rec since Jan 2017.
