### ISSUE TITLE
Encoding of text/plain in example (editorial)

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#186]
https://www.w3.org/Mail/flatten/index?subject=https%3A%2F%2Flists.w3.org%2FArchives%2FPublic%2Fpublic-dwbp-comments%2F2016Jul%2F0025.html&list=public-dwbp-comments

**Comment by xfq** [comment]
The charset parameter has been added to the spec.

**Comment by r12a** [comment]
There looks to be an outstanding question for us, but the document is a Rec since Jan 2017, and the WG disbanded. 👍 to close.
