### ISSUE TITLE
Bopomofo ruby on the right in horizontal text is the norm, not just frequent

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#1864]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/html-ruby/issues/19

**Comment by xfq** [comment]
Indeed. See also https://www.w3.org/TR/clreq/#h-positioning_zhuyin_symbols

**Comment by aphillips** [comment]
fixed
