### ISSUE TITLE
Need to explicitly mention the default placement of ruby with 2 sets of annotations

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#1866]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/html-ruby/issues/20

**Comment by frivoal** [comment]
This is covered in a part of the HTML specification (https://html.spec.whatwg.org/multipage/rendering.html#phrasing-content-3) that this extension specification does not propose changing:

> When a particular part of a ruby has more than one annotation, the annotations should be distributed on both sides of the base text so as to minimize the stacking of ruby annotations on one side.

Without introducing redundancy, it could be mentioned non-normatively in the advisement box at the start of https://www.w3.org/TR/html-ruby-extensions/#rendering that that section has a few existing additional requirements about ruby.

**Comment by aphillips** [comment]
fixed
