### ISSUE TITLE
BP3 should recommend locale-neutral representation

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#187]
https://www.w3.org/Mail/flatten/index?subject=https%3A%2F%2Flists.w3.org%2FArchives%2FPublic%2Fpublic-dwbp-comments%2F2016Jul%2F0028.html&list=public-dwbp-comments

**Comment by r12a** [comment]
Note also btw that the position of the currency symbol is dependent on the locale.  In France it would be normal to write 2000.00 € rather than €2000.00.  Same even when talking about USD when using $, ie. 2000.00 $.

**Comment by aphillips** [comment]
@r12a That's true, but that's only the tip of the iceberg, so to speak. Many things are dependent on locale: decimal symbol, grouping symbol, number of grouping digits, digit shapes, etc. It's because there can be wide variation (sometimes open to misinterpretation) that sending a locale neutral format is preferred for data values.

**Comment by r12a** [comment]
Oh, yes. Didn't mean to imply otherwise.
