### ISSUE TITLE
Mention the need for metadata in multiple human languages

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#19]
https://www.w3.org/Mail/flatten/index?subject=https%3A%2F%2Flists.w3.org%2FArchives%2FPublic%2Fpublic-dwbp-comments%2F2016Jul%2F0033.html&list=

**Comment by xfq** [comment]
Updated text: https://github.com/w3c/dwbp/commit/95d6df13f67da21beb2f8b8ab1aa211d0600dea3

**Comment by r12a** [comment]
The text change seems to address the issue.
The document is a Rec since Jan 2017, and the WG disbanded. 👍  to close.
