### ISSUE TITLE
Best practice for including language and direction metadata?

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#190]
https://www.w3.org/Mail/flatten/index?subject=https%3A%2F%2Flists.w3.org%2FArchives%2FPublic%2Fpublic-dwbp-comments%2F2016Jul%2F0031.html&list=public-dwbp-comments
## 

original version of comment:

> BP3 covers locale-formats, but does not suggest the need to tag natural language text with language and base direction metadata. These are common best practices and necessary for proper presentation and display of content.

**Comment by fsasaki** [comment]
For language information I agree, since there is also a standard mechanism to do that with RDF. For directionality there isn't such a mechanism. What should one suggest?

**Comment by aphillips** [comment]
BP3 covers locale-formats but does not suggest the need to tag natural language text with a language tag and with base direction metadata. Natural language can be indicated via the existing RDF representation. However, there currently exists no good mechanism to indicate base direction. This is seen as a gap in formats such as JSON-LD for which no good generalized solution exists. However, it is an unsolved problem that should be acknowledged (and which might be overcome via other means, such as providing Unicode controls or adding field-specific metadata to document formats).

**Comment by xfq** [comment]
The JSON-LD Working Group has now taken over the issue, see the [i18n namespace](https://www.w3.org/TR/json-ld11/#the-i18n-namespace).
