### ISSUE TITLE
Reference locale-neutral in BP13?

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#191]
https://www.w3.org/Mail/flatten/index?subject=https%3A%2F%2Flists.w3.org%2FArchives%2FPublic%2Fpublic-dwbp-comments%2F2016Jul%2F0027.html&list=public-dwbp-comments

**Comment by xfq** [comment]
Current text: https://www.w3.org/TR/2017/REC-dwbp-20170131/#LocaleParametersMetadata
