### ISSUE TITLE
A number of vocabulary items need language/direction/etc. metadata

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#193]
https://www.w3.org/Mail/flatten/index?subject=https%3A%2F%2Flists.w3.org%2FArchives%2FPublic%2Fpublic-dwbp-comments%2F2016Jul%2F0029.html&list=public-dwbp-comments
## 

original version of comment:

> https://www.w3.org/TR/2016/WD-vocab-duv-20160519/#class-usage
> 
> In the section above, there are a number of natural language field types that should have language and direction metadata associated with them.

**Comment by fsasaki** [comment]
you can express with an RDF literal as an object the language via a language tag, so this is covered. The direction metadata would need a separate field like in the argumentation related to web annotation. We probably will repeat the same discussion on whether the linked data vocabulary is defined mainly for text display or machine readable processing.

**Comment by aphillips** [comment]
@fsasaki Agreed. This should be a consideration though. In addition, I would tend to point out that "machine readable processing" when it pertains to natural language content can often benefit from having language information. If we just mean "transmit some Unicode", then yes a string is sufficient without language (or direction) metadata. But doing things like indexing for FTS or selecting fonts to display the data later are language specific.

This may be a higher-level consideration---i.e. maybe it should be a "Data on the Web Best Practice" :-)

**Comment by fsasaki** [comment]
> This may be a higher-level consideration--

yep - if we convey this as a higher level comment, makes sense. 

> I would tend to point out that "machine readable processing" when it pertains to natural language content can often benefit from having language information. 

sure, and adding the information makes a lot of sense. My point was only that this is possible without the need to define it on the data on the web vocabulary level - it comes with RDF itself.

**Comment by r12a** [comment]
This conversation didn't seem to lead anywhere (and i'm finding it hard to match it to the text of the document).  The document has been published as a WG Note, with the proviso:

> This document presents the most mature version of the Dataset Usage Vocabulary that could be produced in the lifespan of the Data on the Web Best Practices Working Group. At the time of publication, it has remained stable for several months, even after receiving feedback and suggestions from the community. Further clarifications and extensions of this model may be carried out by future working groups.

I propose we close it, possibly with a recycle label(?).
