### ISSUE TITLE
Ruby clarification on specs

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#195]
§ https://github.com/w3c/dpub-pagination/issues/4

**Comment by KatyMawhood** [comment]
Since the dpub group is now closed, I propose raising new issues to the relevant group(s):

The [Publishing Business Group](https://www.w3.org/publishing/groups/publ-bg/)
The [EPUB 3 Community Group](https://www.w3.org/publishing/groups/epub3-cg/)

**Comment by xfq** [comment]
Sent an email asking the status: https://lists.w3.org/Archives/Public/public-i18n-core/2020JanMar/0104.html

**Comment by himorin** [comment]
Target document "Priorities for CSS from the Digital Publishing Interest Group" is owned by "Digital Publishing (dpub) IG" which is not active and replaced by Publishing BG and EPUB3 WG. Also document itself is no longer maintained. Ivan wrote:

> My gut reaction is that this document, by itself, should be closed, but at least the
> work therein shouldn't be lost and should be picked up by the revitalized CG-s.

and no follow-up mail from CC-ed colleagues.

Original intent was to make states in the target document clear, to point that there are multiple specs involved for ruby, and to propose more accurate texts on ruby related issues into the document, but not to change some normative text of spec. This tracker is useful for keeping history, but i18n WG and related teams are working on ruby both to HTML and CSS, independently from the target document.

Closing this tracker (agreed during [weekly call](https://www.w3.org/2021/01/28-i18n-minutes.html#t06)).
