### ISSUE TITLE
Authoring requirement for bidi formatting characters seems bogus

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#197]
§ https://github.com/whatwg/html/issues/709

**Comment by r12a** [comment]
Request for advice sent to Mati and Aharon.

**Comment by himorin** [comment]
PR (https://github.com/whatwg/html/pull/1645) for removing document conformance requirements for bidi characters is merged, also confirmed/accepted by w3c/html and i18n WG at https://github.com/w3c/html/issues/751 .

**Comment by r12a** [comment]
I believe this issue is resolved, and we should close this tracker item.

**Comment by r12a** [comment]
Agreed to close as resolved during telecon.
