### ISSUE TITLE
[css3-text] text-underline-position for Mongolian

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#20]
https://www.w3.org/Mail/flatten/index?subject=text-underline-position+for+Mongolian&list=www-style
## 

Raised by:Richard Ishida
Opened on:2011-03-23

from Koji Ishii, Mar 2011

A question was raised at CSSWG F2F[1] about the underline position[2] for Mongolian. I thought I investigated this before, but couldn't find results and therefore contacted a Mongolian student studying Mongolian word processor. Here's a quick summary of his response.
- Mongolian in vertical flow uses underline, on right
- He's not sure if underline is used for horizontal flow or not
- By looking at the spec[1], probably 'below right' would be the good value for Mongolian

[1] http://lists.w3.org/Archives/Public/www-style/2011Mar/0307.html
[2] http://dev.w3.org/csswg/css3-text/#text-underline-position

**Comment by fantasai** [comment]
Fix checked in! Thanks, @r12a !

**Comment by r12a** [comment]
I think the spec takes this behaviour into account, so we can close the issue.
