### ISSUE TITLE
 Re-investigate "compatibility caseless" matching #1666 

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#206]
§ https://github.com/whatwg/html/issues/1666

**Comment by r12a** [comment]
Here is Domenic's summary:

> browsers are not interoperable
about what type of Unicode case-insensitivity they implement here, with
WebKit even using case-sensitive matching for the radio button case (but
not for the image map case). Data from Blink's use counters reveals
however that the Unicode case-insensitivity is never triggered, and even
ASCII case-insensitivity is triggered extraordinarily rarely.
Additionally, the semantics of these attributes is more like an
identifier than anything else, and so case-insensitive comparison never
really made sense in the first place (it was only done for legacy
Internet Explorer compatibility). As such, we move to converge on
case-sensitive matching in all cases.

The change has been made to WhatWG's HTML doc and to Blink.

**Comment by himorin** [comment]
whatwg/html states to use cases-sensitive match otherwise noted, in https://html.spec.whatwg.org/#case-sensitivity-and-string-comparison
there seems no compatibility caseless matching for now.

**Comment by r12a** [comment]
Agreed to close during telecon as resolved.
