### ISSUE TITLE
i18n-ISSUE-248: terminology related to spaces

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#21]
https://www.w3.org/Mail/flatten/index?subject=Comments+on+CSS3+Text+Decoration&list=www-style
## 

Raised by:Addison Phillips
Opened on:2013-02-01

2.5 "text-decoration-skip": the value "spaces" is defined as:

> Skip white space: this includes regular spaces (U+0020) and tabs (U+0009), as well as nbsp (U+00A0), ideographic space (U+3000), all fixed width spaces (such as U+2000–U+200A, U+202F and U+205F), and any adjacent letter-spacing or word-spacing.

Comments:

the term "regular spaces" should probably just be "space", e.g.:

"... this includes space (U+0020) and tab (U+0009) characters, as well as..."

**Comment by fantasai** [comment]
There are a lot of spaces in Unicode, so I'm not really convinced this change would be an improvement. :)

**Comment by r12a** [comment]
@aphillips are you ok with this?  Fantasai is trying to publish before year end.

**Comment by aphillips** [comment]
This is so minor a quibble, I have no objection to closing it. My underlying thought is that there ARE, as fantasai notes, many spaces in Unicode. The ASCII ones are not special/the others are not irregular.
