### ISSUE TITLE
'deleteWordForwards' and 'deleteWordBackwards' not well defined

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#211]
§ https://github.com/w3c/input-events/issues/72

**Comment by r12a** [comment]
[Telecon] JcK: Add also that logical order should be used when talking about forwards and backwards.

**Comment by himorin** [comment]
on this issue, WG is waiting for a suggestion from i18n on how to adjust the explanatory note text

**Comment by aphillips** [comment]
This issue is waiting on a text suggestion by @r12a.

**Comment by xfq** [comment]
Since @aphillips has confirmed in https://github.com/w3c/input-events/issues/72#issuecomment-2422709724 that it's OK, I think we can close this.
