### ISSUE TITLE
Prevent the use of currency synonyms

### ISSUE THREAD

**Issue by stevenatkin** [w3c/i18n-activity#212]
https://www.w3.org/Mail/flatten/index?subject=i18n-ISSUE-212&list=public-payments-wg

**Comment by ianbjacobs** [comment]
@r12a, the Payment Request API no longer has a currencySystem feature. The specification now says "An [ISO4217] well-formed 3-letter alphabetic code (i.e., the numeric codes are not supported)."

I believe this issue can be closed. Thanks!

cc @rsolomakhin, @danyao, @marcoscaceres

**Comment by himorin** [comment]
No issue raised to payment-request repository.

PaymentCurrencyAmount.currency is defined as ISO4217 and to be validated using IsWellFormedCurrencyCode of ECMAScript. Also an note is added for non-standard 3-letter currency codes.
https://www.w3.org/TR/payment-request/#h-note-9
PR: https://github.com/w3c/payment-request/pull/694

Points mentioned in original email thread are well considered and are taken into consideration to add an note (also to remove PaymentCurrencyAmount.currencySystem for having base registry).

Closing this tracker (agreed during [weekly call](https://www.w3.org/2021/01/28-i18n-minutes.html#t06)).
