### ISSUE TITLE
Improper use of languageCode

### ISSUE THREAD

**Issue by stevenatkin** [w3c/i18n-activity#214]
https://www.w3.org/Mail/flatten/index?subject=i18n-ISSUE-214&list=public-payments-wg

**Comment by ianbjacobs** [comment]
@r12a, languageCode is no longer part of the PaymentAddress interface:
 https://w3c.github.io/payment-request/#paymentaddress-interface

I believe this issue can be closed. Thanks!

cc @rsolomakhin, @danyao, @marcoscaceres

**Comment by himorin** [comment]
No issue raised to payment-request repository.
Similar issue was raised against payment-request repository, and languageCode was removed from PaymentAddress.
https://github.com/w3c/payment-request/issues/608
PR: https://github.com/w3c/payment-request/pull/765

Closing this tracker (agreed during [weekly call](https://www.w3.org/2021/01/28-i18n-minutes.html#t06)).
