### ISSUE TITLE
Rotating text

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#218]
§ https://github.com/w3c/svgwg/issues/260

**Comment by himorin** [comment]
Issue closed following founds in an [another issue (Character counting in text 'x', 'y', 'dx', 'dy', and 'rotate' attributes. #537)](https://github.com/w3c/svgwg/issues/537). Tracker is #606 .

**Comment by aphillips** [comment]
This is the second issue moved to #537, so applying N-R to that issue and our tracker.
