### ISSUE TITLE
Add 'none' value to line-break for traditional Chinese

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#221]
https://drafts.csswg.org/css-text-3/issues-lc-2013#issue-97

**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/5072

**Comment by xfq** [comment]
We have a [line-break: anywhere](https://drafts.csswg.org/css-text-3/#valdef-line-break-anywhere) now, but it's "at-risk" per [Status of this document](https://drafts.csswg.org/css-text-3/#status).

**Comment by xfq** [comment]
History of this value:

* In https://github.com/w3c/csswg-drafts/issues/1171#issuecomment-295522963 `line-break: break-all` was added to css-text
* In https://github.com/w3c/csswg-drafts/issues/1561 it was renamed to `line-break: anywhere`

A use case would be [newspapers in Taiwan and Hong Kong](https://w3c.github.io/clreq/#prohibition-rules-none).

**Comment by xfq** [comment]
Per https://www.w3.org/International/track/actions/908 , raised an GitHub issue at https://github.com/w3c/csswg-drafts/issues/5072

**Comment by xfq** [comment]
CSSWG issue closed. `line-break: anywhere` is not at risk now.

**Comment by r12a** [comment]
Let's close this tracker.
