### ISSUE TITLE
titlecasing digraphs

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#223]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://www.w3.org/Mail/flatten/index?subject=https%3A%2F%2Flists.w3.org%2FArchives%2FPublic%2Fwww-style%2F2015Mar%2F0242.html&list=www-style

**Comment by xfq** [comment]
In https://lists.w3.org/Archives/Public/www-style/2016Oct/0068.html it was resolved that only lowercase letters should be capitalized.
