### ISSUE TITLE
Allow multiple meta-description elements if they have different lang values?

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#236]
§ https://github.com/w3c/html/issues/553

**Comment by himorin** [comment]
whatwg/html is limiting one meta element per the name attribute value. not changed as w3c/html to include language attribute.

https://html.spec.whatwg.org/multipage/semantics.html#meta-description
> There must not be more than one meta element where the name attribute value is an ASCII case-insensitive match for description per document.
