### ISSUE TITLE
Dvorak etc keyboards

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#245]
https://w3c.github.io/uievents-code/

How do Dvorak and other non-standard keyboards fit with this spec?

**Comment by andjc** [comment]
I assume, the don't fit. The spec appears to only discuss physical keyboards, there is no discussion on input frameworks  at all.

**Comment by r12a** [comment]
I think i know the answer to this after a closer reading of the parent spec.  Closing.
