### ISSUE TITLE
cursive shaping breaks and typographic characters

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#249]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/699

**Comment by himorin** [comment]
Close summary: Modification to clarify state was landed (https://github.com/w3c/csswg-drafts/commit/72cf00533ef2d8c9a9537a6a744f4d58d6cea236), and marked as pending into level 4 for (more detailed) sub-grapheme cluster styling.
