### ISSUE TITLE
spaces at the ends of lines in a <span style="unicode-bidi:isolate"> inside a pre are displayed at the wrong end of the line

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#25]
https://bugzilla.mozilla.org/show_bug.cgi?id=1230455
## 

Aharon (Vladimir) Lanin 2015-12-03 23:55:10 PST
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36

Steps to reproduce:

Go to:
```
data:text/html,<pre><span style="unicode-bidi:-moz-isolate; direction:rtl">x.   %0Dy.  %0Dz. </span></pre>
```
Actual results:

The spaces are displayed at the left end of each line.

Please note that this is not the case when the unicode-bidi:-moz-isolate is replaced with unicode-bidi:embed. The latter displays correctly.

Expected results:

The periods in each line should be displayed flush with the left margin, i.e. to the left of the letter, but the spaces should be displayed on the right end of each line.

I believe that this is the correct behavior based on the the Unicode and CSS specs. My reasoning:
- A newline inside a `<pre>` constitutes a bidi paragraph break.
- Thus, each of the lines in the test case is a separate bidi paragraph
- CSS writing modes level 3 says: "the paragraph embedding level must be set [...] according to the direction property of the paragraph’s containing block"
- Thus, each line's paragraph embedding level is 0 (i.e. LTR), even though it is inside the direction:rtl span, because its containing block is the `<pre>`, which has the default direction:ltr, and thus embedding level 0.
- CSS writing modes level 3 says: "[unicode-bidi:isolate] corresponds to inserting an LRI (U+2066), for direction: ltr, or RLI (U+2067), for direction: rtl, at the start of the inline box, and a PDI (U+2069) at the end of the box."
- It also says: "If an inline box is broken around a bidi paragraph boundary (e.g. if split by a block or forced paragraph break), then the HL3 bidi control codes assigned to the end of the box are also added before the interruption and the codes assigned to the start of the box are also added after it. (In other words, any embedding levels, isolates, or overrides started by the box are closed at the paragraph break and reopened on the other side of it.)"
- Thus, each line should be treated as starting with an RLI and having a PDI after the spaces.
- UBA's L1 says: "On each line, reset the embedding level of the following characters to the paragraph embedding level: [...] Any sequence of whitespace characters and/or isolate formatting characters (FSI, LRI, RLI, and PDI) preceding a segment separator or paragraph separator".
- Thus, on each line, the embedding level of the trailing spaces and the PDI should be reset to the paragraph embedding level, which we determined above as 0. This should put both the spaces and the PDI at the right end of the line.

**Comment by r12a** [comment]
test

**Comment by KatyMawhood** [comment]
I propose closing this issue because the source issue, Bug [1230455](https://bugzilla.mozilla.org/show_bug.cgi?id=1230455), is fixed by Bug [1160847](https://bugzilla.mozilla.org/show_bug.cgi?id=1160847).

**Comment by KatyMawhood** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2019/03/28-i18n-minutes.html).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
<b>katy:</b> seems to be fixed<br/>
<b>RESOLUTION:</b> close issue 25<br/>
</details>

**Comment by r12a** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2019/03/28-i18n-minutes.html).

- `RESOLVED:  close issue 25`
<details><summary><i class="differentiate">View the transcript</i></summary>
&lt;Katy> <a href="https://github.com/w3c/i18n-activity/issues/25">https://github.com/w3c/i18n-activity/issues/25</a><br/>
<b>katy:</b> seems to be fixed<br/>
<b>RESOLVED:</b> close issue 25<br/>
</details>
