### ISSUE TITLE
Add dir/lang member on dictionaries whose content is displayed in browser UI

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#251]
§ https://github.com/w3c/payment-request/issues/327

**Comment by marcoscaceres** [comment]
Reopened w3c/payment-request#327

**Comment by aphillips** [comment]
It seems like this got backed out and remains unaddressed in the current CR candidate, so I don't think I18N can say that we're "satisfied" by the outcome. I am removing the `close?` label pending further discussion.

**Comment by r12a** [comment]
@aphillips we need to urgently close this or raise an objection because the WG is moving to a transition.

I thought we decided to ask them to include a section in the spec that lists i18n items that they didn't implement for this version but will return to in the next?  See https://www.w3.org/2021/09/09-i18n-minutes.html#t07  Perhaps we can ask them to do that, and then we close with a recycle label.
