### ISSUE TITLE
i18n-ISSUE-519: Table of contents does not display properly in Safari browser

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#29]
http://www.w3.org/Mail/flatten/index?subject=i18n-ISSUE-519&list=service-workers
## 

Raised by: Steven Atkin, Feb 2016

The table of contents for the specification is not visible when using the Safari browser on Macintosh.

**Comment by ylafon** [comment]
Is it still the case now? IIRC it was a Css implementation issue that no longer exists.
See https://w3c.github.io/ServiceWorker/ and for the latest v1 WD: https://www.w3.org/TR/2019/WD-service-workers-1-20190813/

**Comment by r12a** [comment]
Seems ok to me. I propose to close this issue without raising it in the SW repo.

**Comment by r12a** [comment]
Agreed to close during telecon.
