### ISSUE TITLE
Should we add the ability to query by language or country to watchAvailability()

### ISSUE THREAD

**Issue by stevenatkin** [w3c/i18n-activity#310]
§ https://github.com/w3c/remote-playback/issues/70

6.2.1.3 Getting the remote playback devices availability information
https://w3c.github.io/remote-playback/#getting-the-remote-playback-devices-availability-information

Would there be a need to query remote device playback availability based upon language and our country? I am not sure about this as this API simply queries to see what devices are available to play media remotely. Could we have a situation where there would be some specific hardware that would need to be selected based upon language?

**Comment by duerst** [comment]
I don't understand the details, but it's often the case that copyright for some specific medium is limited to certain countries. As an example, in Japan, I often get black boxes on some Web sites saying "Video not available".

**Comment by stevenatkin** [comment]
The issue that we were after here is whether or not some remote playback device would have some specific language capability that would be utilized in playback. For example, the device might have some specialized set of fonts for showing captions.

**Comment by himorin** [comment]
Spec updated after discussion and agreement by PR https://github.com/w3c/remote-playback/pull/99
