### ISSUE TITLE
Handling non-kana text for rubyAlign with spaceAround or spaceBetween

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#320]
§ https://github.com/w3c/ttml2/issues/251

**Comment by r12a** [comment]
discussion ongoing...

**Comment by r12a** [comment]
The TTML WG conclusion was:

> We will create tests to verify this behaviour and will be open to implementation feedback based on the results of those tests during CR.

That would mean that for spaceBetween you'd see

```
|j a y  c h o u|
```

rather than 

```
|jay    chou| 
```

I have requested information about what feedback was received during CR.

My expectation is that people working with pinyin (or, i suppose, other word-separated writing systems) will normally use the `centre` value, rather than `spaceBetween` or `spaceAround`, so this may be a non-issue.

**Comment by KatyMawhood** [comment]
Since @r12a appears happy with the conclusion of the TTML WG, I propose to close this issue.

**Comment by r12a** [comment]
Bring this up again for the next version of the spec.

**Comment by KatyMawhood** [comment]
@r12a Is there a basic timeline for spec versions that we can use as a prompt?

**Comment by aphillips** [comment]
@KatyMawhood Except in exceptional cases (*cough* CSS *cough*) there usually isn't a pre-determined next version. But any next version of a spec will become visible to us at FPWD. That would seem to be a logical place to review any holdovers?

**Comment by KatyMawhood** [comment]
Sounds like this is already set up via the recycle label. :)

**Comment by r12a** [comment]
Indeed. That's what that label is for.
