### ISSUE TITLE
Subscription request needs to define UTF-8

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#324]
moved to (https://github.com/w3c/websub/issues/89)

**Comment by aphillips** [comment]
@r12a Can you reopen the issue? I can't find a commit that addresses it. I notice that the editor's copy is seriously broken.

**Comment by r12a** [comment]
Done, though i thought you'd be able to do that by adding a comment and clicking on the button that sends the comment and reopens at the same time. Doesn't that work?

**Comment by r12a** [comment]
Closing because @aphillips is satisfied on 31 Mar.
