### ISSUE TITLE
Metadata examples do not include xml:lang (editorial)

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#325]
moved to (https://github.com/w3c/ttml2/issues/271)

**Comment by r12a** [comment]
Some edits were made. Are we ok to close?

**Comment by aphillips** [comment]
No. I made a comment to the contrary. They mixed issues together and didn't address my comment on metadata.

**Comment by r12a** [comment]
@aphillips the issue has been closed by TTML.  Do you still want to change something or should we close this too?

**Comment by r12a** [comment]
Agreed to close during last telecon.
