### ISSUE TITLE
Code points and graphemes in backward deletion

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#349]
§ https://github.com/w3c/input-events/issues/71

**Comment by aphillips** [comment]
I agree that this is backwards. Other examples might include thinks like emoji sequences (with variation selectors) or ZWJ sequences or certain control sequences.

**Comment by r12a** [comment]
Telecon: No objection to sending.

**Comment by himorin** [comment]
suggestions on how to adjust the explanatory note text are posted to issue, waiting WG

**Comment by r12a** [comment]
I'm closing this, since i don't think the further edits suggested by Koji, or my gloss on that, are essential. The issue seems to be satisfactorily resolved.
