### ISSUE TITLE
Incorporate CSS advances into TTML vertical text handling

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#356]
(originally https://github.com/w3c/ttml2/issues/277 but got redirected)

§ https://github.com/w3c/ttml3/issues/9

**Comment by fantasai** [comment]
I agree 100% with everything you've written, @r12a.

**Comment by r12a** [comment]
Cool! Thanks!

**Comment by r12a** [comment]
discussion ongoing...

**Comment by r12a** [comment]
The outcome was that two `sideways-` values of `textOrientation` were removed. However, there was no rapprochement of `writingMode` with CSS syntax, which is a shame.  Values for the latter include  "lrtb" | "rltb" | "tbrl" | "tblr" | "lr" | "rl" | "tb".  There was no addition of `sideways-lr` or `sideways-rl` either.

> The inclusion of new values in tts:writingMode can only be envisaged in a next version of TTML.

So i suppose we close and maybe add a 'raise again later' label.
