### ISSUE TITLE
Default directions in mixed textOrientation should use TR50

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#357]
§ https://github.com/w3c/ttml2/issues/279

**Comment by matial** [comment]
Note that TR50 has no provision for glyphs rotated 90 degrees counterclockwise. This is needed e.g. for sideways text in French as may be found on the edge of books.

**Comment by r12a** [comment]
@matial that's what sideways-left is for, and why it was added as a value of CSS writing-modes (rather than using text-orientation). You can picture the result as if you were taking the horizontal line box(es) and rotating it counter-clockwise. That would give you your French running up the spine of the book. No text-orientation for glyphs using TR50 is involved. All characters lie on their left side, ideographs included.

The sideways- values of writing mode are basically for use with horizontal scripts in mainly these kinds of scenarios, where you want normally horizontal text running up or down a spine or the edge of a figure or some such.

The text-orientation values, and the TR50 defaults, are only used for the vertical- values of writing-modes. See https://www.w3.org/TR/css-writing-modes-3/#text-orientation.

**Comment by r12a** [comment]
This was handled in https://github.com/w3c/ttml2/issues/230, which led to the addition of a reference to TR50.

Close.
