### ISSUE TITLE
Sideways shouldn't be tied to tblr vs tbrl

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#358]
§ https://github.com/w3c/ttml2/issues/280

**Comment by matial** [comment]
I am afraid that this is not only a matter of script. For instance, I have observed (on the edge of books) that for English and Hebrew the rule, without exception, is that the text proceeds from top to bottom, but for French the text proceeds from bottom to top.
I think that Arabic also goes top to bottom, but I have no idea how it goes for other languages written with the Arabic script.

**Comment by r12a** [comment]
@matial as i mentioned in https://github.com/w3c/i18n-activity/issues/357#issuecomment-285161474 you need writing-mode: sideways-lr/rl to rotate horizontal lines of text as you describe, not the vertical- values.  This is a fairly recent change in CSS, that solves a longstanding problem, so you may want to reread https://www.w3.org/TR/css-writing-modes-3/#block-flow

**Comment by r12a** [comment]
discussion ongoing...

**Comment by r12a** [comment]
`textOrientation` `sidewaysLeft` & `sidewaysRight` were removed from the spec.
Close!
