### ISSUE TITLE
where unique key goes [non-I18N]

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#360]
§ https://github.com/w3c/IndexedDB/issues/181

**Comment by r12a** [comment]
+1 to close

**Comment by r12a** [comment]
I think we may be as close as we're going to get with the resolution, but also the spec is now a Rec.  What should we do @aphillips ?

**Comment by xfq** [comment]
The example is being reworked by Joshua (the spec editor) here: https://github.com/w3c/IndexedDB/pull/318

The updated text will enter Indexed Database API 3.0 (Addison's comment was for Indexed Database API 2.0, which is a Recommendation now).

**Comment by r12a** [comment]
The rewording answers my issue. Looks like @aphillips point was answered too. So i propose to close this.
