### ISSUE TITLE
sorted list by code unit

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#362]
§ https://github.com/w3c/IndexedDB/issues/179

**Comment by r12a** [comment]
I think it would be useful to add something to specdev describing the aims and limitations of the sort they are proposing. We'd need to create a succint do/don't sentence, then add a paragraph of explanation, which could include:

> This matches the Array.prototype.sort on an Array of Strings. This ordering compares the 16-bit code units in each string, producing a highly efficient, consistent, and deterministic sort order. The resulting list will not match any particular alphabet or lexicographical order, particularly for code points represented by a surrogate pair.

@aphillips are you up for that?

**Comment by aphillips** [comment]
Satisfied by their PR. Creating action for @r12a's comment in https://github.com/w3c/bp-i18n-specdev/issues/62
