### ISSUE TITLE
list of records ascending order

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#365]
§ https://github.com/w3c/IndexedDB/issues/176

**Comment by r12a** [comment]
Um, isn't this where we suggest use of UBA? (Which is i think not code unit based.)

**Comment by aphillips** [comment]
@r12a I think you mean UCA (Unicode Collation Algorithm)? 

I don't necessarily think that sorting the keys using UCA is required. What is wanted is a fast deterministic sorting. I generally prefer to see the list in code *point* order rather than in (UTF-16) code unit order. But this spec doesn't say anything about what the order is.

**Comment by r12a** [comment]
+1 to close

**Comment by aphillips** [comment]
Satisfied
