### ISSUE TITLE
Message text not localizable

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#377]
§ https://github.com/w3c/webrtc-pc/issues/1605

**Comment by r12a** [comment]
Telecon: Ok to forward.

**Comment by aphillips** [comment]
I marked this `close?` because the WG marked it closed and we didn't follow up. But I do think our friend string-meta may apply here.

**Comment by dontcallmedom** [comment]
@aphillips can this be closed?

**Comment by aphillips** [comment]
I don't agree with the resolution, but we missed the window for following up on it. I'm adding a comment to the issue itself.

**Comment by r12a** [comment]
So, closing this then....
