### ISSUE TITLE
Definition of "Hub" suggests that only 1 hub exists

### ISSUE THREAD

**Issue by joconner** [w3c/i18n-activity#378]
https://w3c.github.io/websub/

1 Definitions
Hub ("the Hub") 

> "The server (URL [WHATWG-URL]) which implements both sides of this protocol. Any hub may implement its own policies on who can use it."

The definition of "Hub" suggests that there is a single hub, "the Hub". However, other parts of the document seem to hint that many hubs are possible. Maybe this just requires a little clarification?

**Comment by r12a** [comment]
Telecon: Ask John to raise this separately. Not an i18n comment.

**Comment by r12a** [comment]
@joconner, we discussed this during the i18n telecon and concluded that it's not an i18n issue. Could you raise it against the spec as a personal comment, please? Thanks. I'll close this here.
