### ISSUE TITLE
Default UA stylesheet for emphasis marks

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#385]
https://www.w3.org/Mail/flatten/index?subject=Default+UA+stylesheet+for+emphasis+marks&list=www-style

**Comment by r12a** [comment]
The doc marks this as accepted, but needing i18n review.
https://drafts.csswg.org/css-text-decor-3/issues-cr-2013#issue-11

https://drafts.csswg.org/css-text-decor-3/issues-cr-2013#issue-12 seems to be the same issue.

**Comment by r12a** [comment]
Current status: Still waiting for information from local experts as to whether emphasis marks should swap sides as language changes.

**Comment by fantasai** [comment]
I will note that underlines do seem to swap sides in Japanese publications: see http://fantasai.tripod.com/www-style/2003/directions/genji2.jpg

**Comment by r12a** [comment]
Seems we have our answer for Korean at https://github.com/w3c/klreq/issues/20. Suggest we close.

**Comment by xfq** [comment]
We haven't had an answer to the swapping-sides-when-mixing-different-languages issue, though.

(Personally, I'm OK with closing this issue. FWIW, during Chinese Layout TF's last telecon, I mentioned this issue, but nobody ever saw cases like this before...)
