### ISSUE TITLE
Proposal for the 'text-emphasis-position' property syntax values

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#387]
https://www.w3.org/Mail/flatten/index?subject=Proposal+for+the+%27text-emphasis-position%27+property+syntax+values&list=www-style

**Comment by r12a** [comment]
CSS doc says 
Open:     Accepted =i18n= Verify assumptions in proposal.
https://drafts.csswg.org/css-text-decor-3/issues-cr-2013#issue-17

**Comment by r12a** [comment]
I think the assumptions in the thread are correct, but it would be useful to get a summary of the current situation from @fantasai as to the current proposal, so that we can review it (since the thread is quite complicated).

**Comment by r12a** [comment]
We have some info-requests out that relate to this:
1. [Are emphasis marks used for Korean, and if so, which side?](https://github.com/w3c/i18n-activity/issues/476)
2. [Position of ruby, text-emphasis, under/overline, etc in vertical-LR writing mode](https://github.com/w3c/clreq/issues/136)

**Comment by r12a** [comment]
It would be helpful, i think, to convert this and similar issues that are email-based to github issues for future tracking and discussion. I think we should ask @fantasai about that.

**Comment by fantasai** [comment]
The current proposal is, as stated in the Response line in the DOC
```
text-emphasis-position: [ over | under ] && [ right | left ]?
```

This means that the side in vertical writing modes can be omitted and is assumed to be `right` when omitted, but the side for horizontal writing modes is required to be stated.

This makes sense if we can assume that `right` is usually the correct answer. If it's frequently wrong, then we might need both arguments to remain required.

**Comment by r12a** [comment]
Original comment closed. Propose to close this too.
