### ISSUE TITLE
Doesn't example 3 in text-underline-position break current UA behavior?

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#388]
https://www.w3.org/Mail/flatten/index?subject=Doesn%27t+example+3+in+text-underline-position+break+current+UA+behavior&list=www-style

**Comment by r12a** [comment]
CSS doc says: Open:     Accepted =i18n= Evaluate whether defaulting omitted auto/under to auto is better than under.
https://drafts.csswg.org/css-text-decor-3/issues-cr-2013#issue-18

**Comment by r12a** [comment]
Current status: This is quite complicated to piece together. It would be nice to have a summary of the final proposal, after agreement with the various parties in the discussion before we pass judgement.

**Comment by fantasai** [comment]
The request to i18n is to evaluate the decision of defaulting to `auto` rather than `under`
- for CJKM in general, via UA style rules
- for declarations which specify a position for vertical writing modes but not horizontal ones

**Comment by r12a** [comment]
Discussed during i18n telecon.  Agreed to close.
