### ISSUE TITLE
skip space and Ethiopic word space

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#393]
https://github.com/w3c/csswg-drafts/issues/1146

**Comment by r12a** [comment]
CSS doc says: Resolved: Bugfix
https://drafts.csswg.org/css-text-decor-3/issues-cr-2013#issue-32

**Comment by fantasai** [comment]
Edits haven't been made yet; but they will be. :) This is the sort of issue that the CSSWG would be like “Do whatever i18n says”.

**Comment by fantasai** [comment]
This is the sort of issue that the CSSWG would be like “Do whatever i18n says”.

**Comment by r12a** [comment]
Fantasai says: closed during LC, no follow-up from i18n afaik.

However, we haven't yet seen the edit that would take care of it.

**Comment by r12a** [comment]
Seen the edit. Advise to close.
