### ISSUE TITLE
Matching input to datalist values

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#396]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/whatwg/html/issues/4814

originally: https://github.com/w3c/html/issues/1011

**Comment by r12a** [comment]
@i18n mtg: Also need to consider tailored matching, eg. for Turkish.  Then what about accent-stripping, etc.?

Also what about IMEs, and typing pinyin/bopomofo?  Mapping wide and narrow FEast chars?

While it can be useful, it is fraught with dangers that implementers should be aware of the dangers and do their best to support local usage.
At a minimum do normalization. Don't use NFKC/D.

This is a nest of snakes you've opened, it looks simple but involves problems that implementers should be aware of in terms of representing local needs, and they should provide implementations that meet those needs.

**Comment by himorin** [comment]
seems no change from w3c/html state to current whatwg/html state.

**Comment by himorin** [comment]
[4.10.5.3.9](https://html.spec.whatwg.org/multipage/input.html#the-list-attribute) just says
> If filtering based on the user's input, user agents should use substring matching against both the suggestions' label and value.

and seems nothing on case nor normalize.

**Comment by r12a** [comment]
I think we should raise this issue against the whatwg HTML.

**Comment by r12a** [comment]
This issue appears to have a resolution but no action has been taken in about 2 years.  We should ask WhatWG to act on it.

**Comment by aphillips** [comment]
This was fixed by my PR https://github.com/aphillips/html/commit/b0135d2aee490ef9d40c8bdffce840353c2e0e08
