### ISSUE TITLE
Use of fillLineGap might cause glyph collisons

### ISSUE THREAD

**Issue by steveatkin** [w3c/i18n-activity#399]
https://github.com/w3c/imsc/issues/254

**Comment by r12a** [comment]
[Steve's original comment]

> It's unclear to me if glyph collisions will occur between the lines. Might we have cases that cause text to become unreadable when a line above contains glyphs that extend below the line that collide with glyphs that extend above a line?

Iiuc, this feature only affects the colouring of the background, rather than the distance between lines. I assume that the latter is taken care of by the main TTML (or other) spec(?)

**Comment by klensin** [comment]
Editorial (I think) It might be helpful if this document were to prominently state/ clarify just what fillLineGap does/ affects.  Even if it is just about colouring between lines, I can imagine that, with some choices of type style ad type colouring, poor choices for this value might cause parts of letters of symbols to become effective invisible.   If that can't occur, it would be helpful for the document to say so.  Conversely, if it can, some cautionary words may be appropriate.

**Comment by r12a** [comment]
Telecon: No objection to sending. Send John's comment.

**Comment by nigelmegitt** [comment]
@klensin The TTWG has been discussing this at w3c/imsc#254 and trying to address https://github.com/w3c/i18n-activity/issues/399#issuecomment-302446435 (which was used as the basis of the issue without the additional context of https://github.com/w3c/i18n-activity/issues/399#issuecomment-302399997 ) but has pretty much given up, on the basis that the group isn't really sure what question you are asking, and some of the alleyways we've wandered down have been rather twisty - i.e. complex and hard to demonstrate. Would you be able to help explain the issue further or ask the question a different way?

Also, now that I've seen https://github.com/w3c/i18n-activity/issues/399#issuecomment-302399997 perhaps I understand slightly better: does it help you if I mention that fillLineGap only affects the background painting area and does not affect line height or "foreground" layout and glyph drawing at all?

**Comment by skynavga** [comment]
Firstly, glyph collisions are already possible, since the marks of a glyph may extend outside the EM square of a font. Second, ``fillLineGap`` has no impact on glyph or line area positioning whatsoever.

**Comment by nigelmegitt** [comment]
We just discussed this at a TTWG F2F meeting and consider the tracked issue w3c/imsc#254 to be closed due to lack of response (for WR comment processing the issue remains open, but is labelled WR-rejected and WR-commenter-no-response). If there is more to do on this please comment on that issue.
