### ISSUE TITLE
i18n-ISSUE-352: normalization of custom property names

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#40]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/4452

**Comment by himorin** [comment]
Closed as invalid, 'case-sensitive' in the state is defined as code-point to code-point comparison without any modification like normalization.

**Comment by aphillips** [comment]
I added a comment to their issue. While I don't have a *normative* problem with their resolution, I do think that the documentation of "case-sensitive" is lacking. Probably we should raise an issue on HTML, if that's the definition everyone is going to use, and put the health warning there. Implementers don't have a problem here (they generally understand what to do), but content authors may be surprised.

**Comment by r12a** [comment]
@aphillips is about to address the root cause, which is related to an HTML issue. So leave open until then.
