### ISSUE TITLE
convertability to Gregorian

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#400]
The current ED starts with an issue:

> New classes and properties are introduced in this revision of OWL-Time. The new elements primarily relate to relaxing the limitation that time position uses the Gregorian Calendar, and are placed in a logical hierarchy in relation to the original elements. While there is inevitably less implementation evidence for these than the elements that were introduced in the 2006 version, the new elements are essential to satisfying key requirements in the revision. However, a small number of other new elements - :MonthOfYear, :hasTime, :hasXSDDuration, :monthOfYear - have been less strongly motivated and tested, so these are formally features at risk pending the accumulation of evidence of implementation.

Many standards use the Gregorian Calendar for the representation of time data (cf. XML Schema) even though other calendric systems exist and are important. One thing that is usually noted is that time values are generally convertible between different timekeeping systems, making Gregorian a useful pivot point.

**Comment by himorin** [comment]
not raised yet to sdw repository, spec is already in REC, ok to close this?
