### ISSUE TITLE
Should generalYear (etc.) be gregorianYear (etc.)?

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#404]
§ https://github.com/w3c/sdw/issues/888

**Comment by plehegar** [comment]
We received a CR Snapshot request for owl-time. Is this issue still on the table or should it be closed?

**Comment by aphillips** [comment]
I am not yet satisfied (I added a detailed comment to their issue and asked for re-open consideration). My comment has not yet been considered by the I18N WG as a whole.

**Comment by aphillips** [comment]
I18N should review this issue and decide whether to close it.

**Comment by aphillips** [comment]
discussed in 2023-12-14, closing
