### ISSUE TITLE
i18n-ISSUE-353: Section 2.1 case sensitivity and normalization

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#41]
https://www.w3.org/Mail/flatten/index?subject=I18N-ISSUE-353&list=www-style
## 

Raised by:Addison Phillips
Opened on:2014-05-29

Section 2.1

http://www.w3.org/TR/2014/WD-css-variables-1-20140506/#syntax

> The values of custom properties, and the values of var() functions substituted into custom properties, are case-sensitive, and must be preserved in their original author-given casing. (Many CSS values are case-insensitive, which user agents can take advantage of by "canonicalizing" them into a single casing, but that isn’t allowed for custom properties.) 

As with I18N-ISSUE-352 the relationship of string identity matching for other textual variations should be mentioned.

**Comment by xfq** [comment]
Current [text](https://drafts.csswg.org/css-variables/#syntax):

> The values of custom properties, and the values of `var()` functions substituted into custom properties, are <em>case-sensitive</em>, and must be preserved in their original author-given casing. (Many CSS values are <a href="https://infra.spec.whatwg.org/#ascii-case-insensitive">ASCII case-insensitive</a>, which user agents can take advantage of by "canonicalizing" them into a single casing, but that isn’t allowed for custom properties.)
