### ISSUE TITLE
Unicode Normalization health warning needed?

### ISSUE THREAD

**Issue by bert-github** [w3c/i18n-activity#410]
**This is a tracker issue.  Contribute to the actual discussion at the following link:**

https://github.com/w3c/poe/issues/212

Only discuss things here if they are i18n WG internal meta-discussions about the issue.

In the section ["Policy Provenance"](https://w3c.github.io/poe/model/#provenace), the "ODRL Information Model" allows human-readable strings as optional, informative annotations on Policies, in particular in the form of Dublin Core metadata terms "creator", "description" and "coverage". ODRL does not talk about normalization of these strings (and neither does JSON-LD, which may be used to serialize ODRL) and also does not warn about possible misreadings of characters.

On the other hand, these strings are not used in any way by ODRL itself, so this is probably not a security issue.

**Comment by bert-github** [comment]
Removed "pending" label. The issue is now tracked in the poe repository (see link above).

**Comment by bert-github** [comment]
Added "Close?" label.

The POE WG added this to the draft:

> Note: The string values used in the Dublin Core metadata properties are not designed for comparison of Policy metadata, as they may not be normalised.

**Comment by r12a** [comment]
Telecon: Agreed to close.
