### ISSUE TITLE
Should the character sets be minimum font requirements?

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#414]
**This is a tracker issue.  Contribute to the actual discussion at the following link:**

https://github.com/w3c/imsc/issues/236

Only discuss things here if they are i18n WG internal meta-discussions about the issue.

**Comment by klensin** [comment]
I'm troubled, going forward, about the inclusion of the non-ASCII characters in Latin-1 in the global minimal collection.  While that is certainly justified historically, for many countries, the whole goal of i18n efforts is to allow their populations to exclusively use their own languages and scripts online.  From that perspective, they don't like the requirement to support ASCII very much, but ASCII is easily justified on the basis of protocol element requirements such as the elements of HTML, XML, and assorted transport protocols.   But it is difficult to strongly justify (non-ASCII) Latin-1 on that basis: if the argument is that a given font cannot support all Unicode code points that have graphical representations and therefore that a subset must be chosen, selecting a font that excludes some locally-required glyphs in favor of non-ASCII Latin-1 ones is not an obviously reasonable choice no matter what statistics that are historically biased toward western European languages seem to indicate.

**Comment by r12a** [comment]
This appears to have run stale. Closing.
