### ISSUE TITLE
"valid email address" doesn't allow IDNs…

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#417]
**This is a tracker issue.  Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/html/issues/538

Only discuss things here if they are i18n WG internal meta-discussions about the issue.

**Comment by himorin** [comment]
whatwg/html states as one before PR https://github.com/w3c/html/pull/881 is applied.

**Comment by r12a** [comment]
Agreed to close during telecon in favour of upcoming issues arising from #607
