### ISSUE TITLE
allow input type="email" to accept unicode values

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#418]
**This is a tracker issue.  Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/html/issues/845

Only discuss things here if they are i18n WG internal meta-discussions about the issue.

**Comment by r12a** [comment]
See this PR https://github.com/w3c/html/pull/1163#event-1446916121 (review)

Is this a satisfactory resolution?

**Comment by himorin** [comment]
I think it's #607 for whatwg/html

**Comment by r12a** [comment]
Agreed to close during telecon in favour of upcoming issues arising from #607
