### ISSUE TITLE
Clarify the charset constraints on email addresses

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#419]
**This is a tracker issue.  Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/html/pull/881

Only discuss things here if they are i18n WG internal meta-discussions about the issue.

**Comment by himorin** [comment]
The point of changing one requirement  (from "user agents may present punycode as IDNs in the interface" to a should) is also landed to whatwg/html: 
https://html.spec.whatwg.org/multipage/input.html#e-mail-state-(type=email)
> in particular, user agents should convert punycode in the domain labels of the value to IDN in the display and vice versa.

other changes in w3c/html is not landed to whatwg/html.

**Comment by r12a** [comment]
Agreed to close during telecon.
