### ISSUE TITLE
Content language, not document language

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#42]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/1845

**Comment by r12a** [comment]
The original questions behind this issue have been clarified, so i think we should close.

**Comment by plehegar** [comment]
ping? shouldn't this be closed?

**Comment by r12a** [comment]
I think it should, indeed. I'll therefore close it.

(fwiw, we have begun a sweep of our tracker database to identify and close stale issues such as this.)
