### ISSUE TITLE
What type of equality checking is being performed for options.

### ISSUE THREAD

**Issue by stevenatkin** [w3c/i18n-activity#424]
**This is a tracker issue.  Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/push-api/issues/275

Only discuss things here if they are i18n WG internal meta-discussions about the issue.

**Comment by himorin** [comment]
change made to solve i18n review comment
https://github.com/w3c/push-api/commit/93b65a9b3794774efbe6a0fa39885f4c7915ed76
