### ISSUE TITLE
TTML2 > 2017-09-30

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#428]
https://www.w3.org/TR/2017/WD-ttml2-20170630/

Dear I18N,

The W3C Timed Text Working Group has recently published a new working draft of the Timed Text Markup Language 2 (TTML2).

https://www.w3.org/TR/2017/WD-ttml2-20170630/

TTML2, provides a standardized representation of a particular subset of textual information with which stylistic, layout, and timing semantics are associated by an author or an authoring system for the purpose of interchange and processing.
In addition to being used for interchange among legacy distribution content formats, TTML Content may be used directly as a distribution format, providing, for example, a standard content format to reference from a <track> element in an HTML5 document, or a <text> or <textstream> media element in a [SMIL 3.0] document.

The TTML2 specification updates the TTML1 specification by adding vocabulary and semantics to address more of its core requirements, including the addition of support for:

     raster images (both foreground and background)
     author supplied fonts
     audio descriptions and text to speech
     ruby text annotations
     improved vertical line layout
     text emphasis, kerning, letter spacing, shadows, and variants
     inline block layout
     stereoscopic presentation (for 3-D viewing)
     high definition resolution (HDR) presentation
     continuous animation
     hyperlinks
     conditional element semantics
     improved metadata extensibility
     formalized intermediate document syntax
     various other improvements and bug fixes

The TTWG invites you to review this draft, and requests comments to be received by 30 Sept 2017. These comments will be used to fulfill the W3C Process [3] requirement for Wide Review of drafts, and  Horizontal Review [4]  prior to publication as Candidate Recommendation.

If you wish to make comments regarding this document, please send them to public-tt@w3.org <mailto:public-tt@w3.org?subject=%5Bttml%5B> with [ttml2] at the start of your email's subject. All comments are welcome, however the scope of review will be mainly focused on the new features introduced in TTML2.

A cumulative summary of all changes applied to this version since the current (TTML1, 2nd Edition) Recommendation was published is available for your convenience [5].

[1] TTML2 latest version https://www.w3.org/TR/ttml2/ [2] TTML1 Recommendation https://www.w3.org/TR/ttml1/ [3] W3C Process https://www.w3.org/2017/Process-20170301/
[4] Horizontal Review
https://www.w3.org/Guide/Charter.html#horizontal-review
[5] https://www.w3.org/TR/2017/WD-ttml2-20170630/ttml2-changes.html

Kind regards,

On behalf of Nigel Megitt, co-Chair, W3C Timed Text Working Group Thierry Michel, Staff Contact for TTWG.

**Comment by himorin** [comment]
proposing close that TTML2 1st ed is REC (2018/Nov/8).
2nd ed HR request is w3c/i18n-activity#823
