### ISSUE TITLE
No way to set the underline width/thickness

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#432]
There's no way to set the thickness of the line underlining text in a `text-decoration: underline`.

**Do not add a comment here, use the following link to make comments visible on the original thread:**
https://github.com/w3c/csswg-drafts/issues/239

**Comment by fantasai** [comment]
https://drafts.csswg.org/css-text-decor-4/#text-decoration-width-property

**Comment by fantasai** [comment]
I cannot believe I still haven't published FPWD on that. :( Was supposed to happen this time last year.

**Comment by r12a** [comment]
The original issue is now closed, since there is text in the location indicated by fantasai above.
