### ISSUE TITLE
Emphasis marks and auto-hiding ruby annotation

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#459]
If the annotation of a character is autohidden, where should the emphasis mark be drawn for this character?

**Do not add a comment here, use the following link to view the thread, and make comments on the original email thread:**
https://www.w3.org/Mail/flatten/index?subject=Emphasis+marks+and+auto-hiding+ruby+annotation&list=www-style

**Comment by fantasai** [comment]
This was answered by Murakami, so I think it can be closed, no?
  https://lists.w3.org/Archives/Public/www-style/2017Apr/0020.html

**Comment by r12a** [comment]
For the record, here is Murakami-san's reply:

> I agree that the Gecko's behavior is pretty good, and I think the emphasis mark position should be consistent within a ruby element (empty annotations should match the behavior of auto-hidden).
> 
> So both
>     `<em>ああ<ruby><rb>振<rb>り<rb>仮<rb>名<rt>ふ<rt>り<rt>が<rt>な</ruby>ああ</em>`
>     (auto-hidden ruby annotation for "り")
> and
>     `<em>ああ<ruby><rb>振<rb>り<rb>仮<rb>名<rt>ふ<rt><rt>が<rt>な</ruby>ああ</em>`
>     (empty ruby annotation for "り")
> should have the same result:
> 　　、、、、
> 、、ふ　がな、、
> ああ振り仮名ああ
> 
> I think this behavior is reasonable for readability, and also because of the ruby layout structure (similar to the table structure, the cell position in a row should not change when a cell in the previous row is empty).

I propose we close this issue, however it may be useful to capture the decision in jlreq or some supplement.
