### ISSUE TITLE
Make dir isolate by default

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#460]
**This is a tracker issue.  Contribute to the actual discussion at the following link:**
Only discuss things here if they are i18n WG internal meta-discussions about the issue.

Safari: https://bugs.webkit.org/show_bug.cgi?id=134630 FIXED !

Edge: Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10954071/  OBSOLETE

**Comment by r12a** [comment]
Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10954071/

**Comment by xfq** [comment]
Why is this issue labelled `clreq` (instead of `alreq`)?
