### ISSUE TITLE
Which side of the line do Mongolian ruby annotations appear normally?

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#465]
**This is a tracker issue.  Contribute to the actual discussion at the following link:**

Only discuss things here if they are i18n WG internal meta-discussions about the issue.

§ https://github.com/w3c/mlreq/issues/4

**Comment by himorin** [comment]
https://github.com/w3c/csswg-drafts/issues/1042 had closed with proposer satisfied.
add close? to this, and also propose to close original https://github.com/w3c/mlreq/issues/4
