### ISSUE TITLE
Why reduce accesskey values to a single code point?

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#482]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/html/issues/1022

**Comment by himorin** [comment]
[6.5.2 The accesskey attribute](https://html.spec.whatwg.org/multipage/interaction.html#the-accesskey-attribute)
says 
> If specified, the value must be an ordered set of unique space-separated tokens that are case-sensitive, each of which must be exactly one code point in length.

This state does not require any procedure to reduce accesskey values, but may remain in conflict with i18n-tests https://www.w3.org/International/tests/repo/results/accesskey#multiple ?

**Comment by r12a** [comment]
I propose we close this tracker (issue already closed) and refer instead to issues being prepared for the WhatWG spec.

**Comment by r12a** [comment]
Agreed to close during telecon.
