### ISSUE TITLE
What do 'character key' and 'printable' mean?

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#484]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/wcag21/issues/386

**Comment by r12a** [comment]
I think we should close this. I think they fixed the issue reported.  Also the repo has been archived, so they've moved on.

**Comment by xfq** [comment]
Agreed.

Updated text: https://www.w3.org/TR/WCAG21/#character-key-shortcuts
