### ISSUE TITLE
AMOA rather than UAOA ?

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#490]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

https://www.unicode.org/review/pri359/

---

The following comment was sent to the Unicode feedback list. No pointer to that comment is available, so i'm including the approximate text below (approximate because after hitting the submit button i'm no longer able to see the actual text).

http://www.unicode.org/reports/tr53/

> The Unicode Arabic Mark Ordering Algorithm (UAOA) 

I find it difficult to figure out how one should pronounce UAOA and difficult to pronounce either way.  I think AMOA would be easier.

**Comment by r12a** [comment]
Raised as a personal comment. See http://www.unicode.org/review/pri359/

**Comment by behnam** [comment]
I submitted a long individual feedback. Here's the part related to this issue:

----

# 2. Scope of the algorithm

The scope of the algorithm is not clear, neither in its title nor in the language.

The name “Unicode Arabic Mark Ordering Algorithm” is suggesting that this is expected to be the only way Arabic Marks should be ordered in Unicode. That’s clearly not the case. In fact, the document is proposing an algorithm for “reordering” Arabic Marks (not just how they should be ordered) to solve a problem in “rendering” of the script. The title need to be clear about this. Maybe “Unicode Arabic Mark Reordering Algorithm for Rendering” (AMRAR)?

Similarly, the Section 2 “Background” doesn’t clarify the scope of the algorithm and only explains how something is not working for some specific application with the existing normalization methods.

**Comment by r12a** [comment]
The acronym was changed to AMTRA, which is easily to pronounce. Recommend we close this.
