### ISSUE TITLE
Shadda display position

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#491]
5.2 Shadda
http://www.unicode.org/reports/tr53/

> however it should be displayed closer to the base than the vowels

As section 5.3 goes on to say, that is not always true. 

I suspect what is meant is either:

1. however it should often be displayed closer to the base than the vowels, or
1. however it should be displayed closer to the base than the vowels, apart from those cases described in 5.3,  or
2. however it should be ordered closer to the base than the vowels

---
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

**Comment by behnam** [comment]
My guess is that the claim in 5.2 is *extended* by the additional rule in 5.3 by the authors.

But I agree that it would be better to explicitly mention the possible exception (depending on style) in 5.2 directly, though.

**Comment by behnam** [comment]
I think the document covers the issue here, and it would be more clear when it's updated about the rendering scope of it. I didn't submit any feedback and think we can just close this issue and wait to review the next version of the doc.

**Comment by r12a** [comment]
Waiting label added. Revisit after document update published.

**Comment by r12a** [comment]
In revision 2 the text is unchanged, so we should send this comment.
