### ISSUE TITLE
Check compatibility of UAOA with NFC

### ISSUE THREAD

**Issue by behnam** [w3c/i18n-activity#495]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

https://www.unicode.org/review/pri359/

---

1. Overview
http://www.unicode.org/reports/tr53/

> This algorithm is the simplest algorithm that matches user expectations,
stays within the stability requirements of Unicode, correctly renders data in normalized forms,
and renders all canonically equivalent sequences the same way.

## "stays within the stability requirements of Unicode"

This needs to be checked. Since the algorithm uses NFD and then reorders marks and brings any MCM mark to the front of the list, this can break actually break stability by resulting in the following:
```
UAOA(NFC(x)) ≠ NFC(UAOA(y))
when NFC(x) = NFC(y)
```
If there are `x` and `y` that this can happen, then this claim would be invalid and misleading.

**Comment by behnam** [comment]
I submitted a long individual feedback. Here's the part related to this issue:

----

# 3. Consequences of the Algorithm: Normalization

The draft proposal is not clear about the effects of applying the algorithm on text. Specially, for strings X for which this algorithm is useful, we have UAOA(toNFC(X)) ≠ toNFC(UAOA(X)).

So, although the behavior of the algorithm can be stabilized over Unicode verions, it’s very important how and when it’s applied to the text, since it changes a text in normalized form to a non-normalized form. Therefore, in terms of normalization, the algorithm cannot be considered stable at all. The document needs to be clear about this, even though it’s obvious from a technical point of view.

**Comment by r12a** [comment]
Reopening for tracking.

**Comment by r12a** [comment]
Since it's now clear (in version 2) that this is purely a transient, internal ordering for the rendering pipeline, can we close this issue?
