### ISSUE TITLE
UAOA is not clear about justification and scope

### ISSUE THREAD

**Issue by behnam** [w3c/i18n-activity#496]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

https://www.unicode.org/review/pri359/

---

1. Overview
http://www.unicode.org/reports/tr53/

> This algorithm is the simplest algorithm that matches user expectations,
stays within the stability requirements of Unicode, correctly renders data in normalized forms,
and renders all canonically equivalent sequences the same way.

## "matches user expectations"

It is not clear which user and what use of characters and encoding this phrase is referring to. In general, the document is focused on "Quranic" use cases more than modern and diverse set of languages using the script.

Also, it is not answering the concerns about auto-reordering marks after user input the marks in a specific order. Basically, it may be an optional feature for an advanced keyboard or a Quran publishing application, but not for every rendering of text in Arabic script.

## "correctly renders data in normalized forms"

This again goes to the use case issue. There is no evidence of what "correct" means here. In fact, the Unicode standard has been expecting users to encode text based on the existing stable normalization behavior, meaning that if user puts "small seen above" after a "fatha", then *mean* that "small meem" is presented after "fatha" and that's the *correct* behavior.

This statement is claiming that having <fatha, small seen above> sequence is *incorrect*, and <small seen above, fatha> is correct. This is not based on any data, and, in fact, the method proposed to do override the algorithm (CGJ) is a sign that there is the need for having both sequences supported eventually. This means that it is not an encoding issue, but a text-entry issue limited to very specific use-cases.

**Comment by khaledhosny** [comment]
I don’t think the issue UAOA is trying to fix is limited to Quran. Take the very common mark sequence <U+0651 ARABIC SHADDA, U+064E ARABIC FATHA>, if you normalize it (NFC or NFD) it will come out in the reverse order:
```python
[hex(ord(u)) for u in unicodedata.normalize("NFC", "\u0651\u064e")]
['0x64e', '0x651']

[hex(ord(u)) for u in unicodedata.normalize("NFD", "\u0651\u064e")]
['0x64e', '0x651']
```

This means fonts and/or layout engines need to work around this, otherwise any process applying normalization to the text will break the order of the marks and subsequently their positioning, else they will be technically in violation with the spec since canonically equivalent strings are not treated the same.

**Comment by behnam** [comment]
Right, @khaledhosny. No one is saying "there's no problem with encoding of Arabic script in Unicode". The comments are all regarding the solution, which is the draft UTR.

**Comment by behnam** [comment]
I submitted a long individual feedback. Here's the part related to this issue:

----

# 2. Scope of the algorithm

The scope of the algorithm is not clear, neither in its title nor in the language.

The name “Unicode Arabic Mark Ordering Algorithm” is suggesting that this is expected to be the only way Arabic Marks should be ordered in Unicode. That’s clearly not the case. In fact, the document is proposing an algorithm for “reordering” Arabic Marks (not just how they should be ordered) to solve a problem in “rendering” of the script. The title need to be clear about this. Maybe “Unicode Arabic Mark Reordering Algorithm for Rendering” (AMRAR)?

Similarly, the Section 2 “Background” doesn’t clarify the scope of the algorithm and only explains how something is not working for some specific application with the existing normalization methods.

# 3. Consequences of the Algorithm: Normalization

The draft proposal is not clear about the effects of applying the algorithm on text. Specially, for strings X for which this algorithm is useful, we have UAOA(toNFC(X)) ≠ toNFC(UAOA(X)).

So, although the behavior of the algorithm can be stabilized over Unicode verions, it’s very important how and when it’s applied to the text, since it changes a text in normalized form to a non-normalized form. Therefore, in terms of normalization, the algorithm cannot be considered stable at all. The document needs to be clear about this, even though it’s obvious from a technical point of view.

**Comment by r12a** [comment]
Reopening for tracking.
