### ISSUE TITLE
Use of Arabic Reordering in text editing

### ISSUE THREAD

**Issue by behnam** [w3c/i18n-activity#497]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://www.unicode.org/review/pri359/

**Comment by behnam** [comment]
Submitted this via the online form:

----
Subject: Feedback on Proposed Draft UTR #53 — Revision 1
Status: Liaison Contribution - W3C i18n WG

# Using UAOA in Text Editing
On Section 5.6 “Other uses for UAOA”, we have:

> UAOA is very useful in implementations of backspacing in cases where there is no external information available about the original order in which the text was entered.

For an average user of modern languages using the script, reordering the marks entered on a keyboard would be unexpected behavior.

Basically, the document is suggesting that when user authors a text file with Arabic Marks put in a specific order, when the files is closed and reopened, the backspace should behave differently from the previous session.

Also, it is not clear at all if UAOA will be useful in a text editing scenario. The claim for UAOA to be "very useful" needs some evidence, like existing implementation or some other data to support it.

From the language and examples of the document, it looks like the usage of the algorithm is too focused on one application, Quranic text, and the claims are related only to that specific application of the script.

**Comment by r12a** [comment]
Reopening, because the WG will want to track this.

**Comment by r12a** [comment]
Some editorial work was done on the relevant section. Can we close this now?
