### ISSUE TITLE
Scope of UTR #53 vs the algorithm UAOA

### ISSUE THREAD

**Issue by behnam** [w3c/i18n-activity#499]
P**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

https://www.unicode.org/review/pri359/

**Comment by behnam** [comment]
I submitted a long individual feedback. Here's the part related to this issue:

----

# 1. Scope of the PDUTR

It looks like the PDUTR is the first UTR focused on details of rendering of Unicode text (besides the text of the Unicode Standard). Arabic is only one of the scripts that need some special attention (possibly reordering of the characters in memory) for rendering. It could be a better approach to have a document (UTR) focused on text rendering, which would also contain this algorithm for Arabic script, and would collect other best-practices over time, for other issues of rendering Arabic script, as well as other scripts.

**Comment by r12a** [comment]
Reopening so that the i18n WG can track this.
