### ISSUE TITLE
i18n-ISSUE-422: start/end linked to left/right

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#5]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=28257
http://www.w3.org/TR/webvtt1/#other-features
## 

Raised by:Addison Phillips
Opened on:2015-02-26

In section 1.3 there is feature for defining the width and alignment of text. The keywords used are 'start' and 'end', which is great. However, the text describing this feature implies that 'start' is always 'left' and end is always the opposite side. Here's what the text says:

> The first cue has its cue box left aligned at the 10% mark of the video viewport width and the text is left aligned within that box - probably underneath a speaker on the left of the video image. "start" alignment of the cue box is the default for start aligned text, so does not need to be specified in "position". The second cue has its cue box right aligned at the 90% mark of the video viewport width. The same effect can be achieved with "position:55%,start", which explicitly positions the cue box. The third cue has middle aligned text within the same type of cue box as the first cue.

Explicit support for text directionality should be provided and a clear linkage established between direction of the text and 'start'/'end' positioning.

**Comment by r12a** [comment]
Needs Addison's review.
Richard Ishida, 23 Jul 2015, 11:13:04

i'm happy to close.
Richard Ishida, 16 Nov 2015, 13:33:35

Not happy yet. Added comment to the issue.
Addison Phillips, 23 Nov 2015, 18:35:10

There has been another round of edits. See https://w3c.github.io/webvtt/#example-0c2976c9
Is it possible to close yet?
Richard Ishida, 16 Mar 2016, 13:24:47

**Comment by aphillips** [comment]
Close enough.
