### ISSUE TITLE
UAs may have somewhat more liberal handling of the dir attribute than the spec does

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#506]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/whatwg/html/issues/2769

**Comment by xfq** [comment]
I agree with Richard's comment in https://github.com/whatwg/html/issues/2769#issuecomment-335190293

**Comment by aphillips** [comment]
Closed because the parent issue is closed (yay 🍾 )
