### ISSUE TITLE
DNT Extension syntax unclear; exclude apostrophe?

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#508]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/dnt/issues/62

Due to a process slip, the following 3 comments should be viewed as part of the DNT response.

**Comment by royfielding** [comment]
Those are octets. Not JSON and not Unicode.

**Comment by aphillips** [comment]
No, the spec clearly says characters and the serialization is JSON. Besides, my point remains regardless of if they were octets or characters. The names aren't clear. And apostrophe has meaning in JSON and maybe should be reserved?

**Comment by royfielding** [comment]
DNT-extensions is the ABNF for what octets are allowed as extensions to the DNT field-value, which is an HTTP header field in US-ASCII. There is no expectation of natural language. The all-caps names in that comment are ABNF syntax rules known to anyone implementing HTTP.

  https://tools.ietf.org/html/rfc5234#page-13

and in any case are just comments to explain what isn't included in the normative range of octets.

**Comment by himorin** [comment]
reply was made and raised issue marked as wontfix

I think reply is correct and propose to close
3.2 Formal Syntax section states specification in ABNF and WebIDL, and pointed lines are valid ABNF syntax.
