### ISSUE TITLE
Diregarding status: language negotiation needed?

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#510]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/dnt/issues/61

Due to a process slip, the following comment should be viewed as part of the DNT response.

**Comment by royfielding** [comment]
It is a Web resource. How servers decide what content to deliver to which users is far outside the scope of TPE.

**Comment by himorin** [comment]
raised issue got comment as out of scope

I personally think there should be some additional text to state out of scope etc.

**Comment by r12a** [comment]
The latest published version of this spec is a [WG Note](https://www.w3.org/TR/2019/NOTE-tracking-dnt-20190117/).

**Comment by aphillips** [comment]
Closed in 2021-08-05 teleconference (unsatisfied, recycle)
