### ISSUE TITLE
Bad link to RTL script information

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#511]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/low-vision-a11y-tf/issues/77

**Comment by himorin** [comment]
pointed link was fixed by commit https://github.com/w3c/low-vision-a11y-tf/commit/94c12fff222c1bf602d9a106b30bd89dc1dadc35
raised issue is not closed, but close this as satisfied?

**Comment by r12a** [comment]
I'm happy with the fix. Suggest we close.
