### ISSUE TITLE
Support for isolation & dir=auto in Edge

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#515]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following links:**

dir isolation request: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/32394604-support-bidi-isolation-for-elements-with-dir-attri

dir=auto request: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/10784463-support-dir-auto

**Comment by xfq** [comment]
Should we close this, given that Edge will be Chromium-based?

**Comment by r12a** [comment]
Microsoft appear to have removed the bug database. Clicking on the above links gives the message: This UserVoice instance is no longer available.

Therefore, seems there's no point to keeping this open.
