### ISSUE TITLE
Allow multiple meta-description elements if they have different lang values?

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#518]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/html/issues/553

**Comment by KatyMawhood** [comment]
I proposed closing this issue because multiple meta descriptions are now allowed in [w3c/html#553](https://github.com/w3c/html/issues/553) via [w3c/html#1161](https://github.com/w3c/html/pull/1161).

**Comment by r12a** [comment]
We need to check whether this is in the WhatWG html spec. If not, then we need to perhaps raise the issue there.

**Comment by himorin** [comment]
seems same as https://github.com/w3c/i18n-activity/issues/236, close?

**Comment by aphillips** [comment]
Resolved
