### ISSUE TITLE
Abstract wording inexact

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#521]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

https://github.com/w3c/csswg-drafts/issues/3829

**Comment by KatyMawhood** [comment]
Since this spec is now a Rec, can I propose that either (1) raise a new issue in [css-drafts](w3c/csswg-drafts/issues), or (2) close this issue.

**Comment by r12a** [comment]
CSS Writing Modes 4 isn't a Rec, it's a CR. CSS Writing Modes 3 is the Rec.

**Comment by xfq** [comment]
Both L3 and L4 are in CR now...

**Comment by aphillips** [comment]
https://www.w3.org/International/track/actions/795 addressed by creating CSS 3829 (linked above)

**Comment by xfq** [comment]
CSS issue closed, with fixes to both L3 and L4. I propose that we close this issue.

**Comment by himorin** [comment]
note, PR for fix is https://github.com/w3c/csswg-drafts/pull/4132

**Comment by r12a** [comment]
Agreed to close during telecon.
