### ISSUE TITLE
When vertical text mode, are SC 1.4.8/1.4.12 applicable as they are?

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#523]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/wcag21/issues/657

**Comment by himorin** [comment]
State was updated to note implicit western language bias, PR https://github.com/w3c/wcag21/pull/729

**Comment by r12a** [comment]
This thread is over 2 years old and the repo has been archived. I'm inclined to close this issue.
