### ISSUE TITLE
Resources for text overflow/ellipsis behavior?

### ISSUE THREAD

**Issue by behnam** [w3c/i18n-activity#524]
International text layout and typography index
http://w3c.github.io/typography/

Gap analysis checklist
https://w3c.github.io/typography/gap-analysis/

Looks like we don't have any item that covers text overflow/ellipsis behavior in neither the typography index nor gap-analysis.

We already have *Line breaking* and *Hyphenation* in both, though.

**Comment by r12a** [comment]
In my own script notes i use a subsection "Abbreviation & ellipsis" (eg. https://r12a.github.io/scripts/hangul/#abbrev), but until we clearly have enough for a separate section, i think we can store information in the above documents under "Other paragraph features".
