### ISSUE TITLE
text-overflow: ellipsis when a word of different direction was truncated

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#526]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/2125

**Comment by himorin** [comment]
Change (https://github.com/w3c/csswg-drafts/commit/cd64ae17cb4c509b4e85dbfc307e667a82c689de) made to add clear example to show how truncation should be implemented.

**Comment by aphillips** [comment]
We were satisfied in [this comment](https://github.com/w3c/csswg-drafts/issues/2125#issuecomment-359212354)
