### ISSUE TITLE
A new property for text decorations to skip ink #962

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#531]
Proposal for a property to skip ink in text decoration.

**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/962

**Comment by r12a** [comment]
This has been deferred to level 4.

**Comment by xfq** [comment]
CSSWG issue closed.

A `text-decoration-skip` shorthand and its sub-properties have been added to L4: https://drafts.csswg.org/css-text-decor-4/#text-decoration-skipping

**Comment by aphillips** [comment]
Fixed
