### ISSUE TITLE
label property should allow internationalized text #437 

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#533]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/web-annotation/issues/437

**Comment by r12a** [comment]
This was only a tracker. The documents in this series are now all Recommendations. I propose we close this issue.

**Comment by himorin** [comment]
Just note: Original issue was reopened and got Errata label.
