### ISSUE TITLE
[css-text] Questionable Thai words #2455 

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#538]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/2455

**Comment by himorin** [comment]
change made, "fixed the typo in the Thai example and added the variations in handling compound words as an example of UA tailoring for line-break values strict vs. loose.".
css-text:
  https://github.com/w3c/csswg-drafts/issues/2455#issuecomment-375477036
  https://github.com/w3c/csswg-drafts/commit/a58db9101fcddf4f930c5fb8bbe06640843ac3e9
wpt:
  https://github.com/web-platform-tests/wpt/issues/13329

**Comment by aphillips** [comment]
Fixed
