### ISSUE TITLE
[css-text-3] line breaks and ideographic space #2500 

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#540]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/2500

**Comment by himorin** [comment]
Change (https://github.com/w3c/csswg-drafts/commit/f55dc746ad6d18264916591d04f88038a6cf0bbb) made and test added to wpt (https://github.com/web-platform-tests/wpt/pull/13338) to note about U+3000 handling to match with ones in JLReq.

**Comment by aphillips** [comment]
Fixed
