### ISSUE TITLE
[css-inline] Cursive drop-caps

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#543]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/2399

**Comment by aphillips** [comment]
This issue was closed by CSS, but @fantasai notes that there's no evidence from e.g. N'Ko. @r12a added the `advice-requested` label in 2019. My instinct is that this is done.

@r12a any reason to keep this open?

**Comment by aphillips** [comment]
@r12a bringing this back to your inbox top. I don't see a reason to keep this open?
