### ISSUE TITLE
[css-text] hanging punctuation: ink vs scrollable overflow #2398 

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#545]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/2398

**Comment by himorin** [comment]
Change (https://github.com/w3c/csswg-drafts/commit/f37e0b0d7b0ec22dab3bd57e512dbe533f28448d) made and test added to wpt (https://github.com/web-platform-tests/wpt/pull/11375) to define hanging punctuation as scrollable overflow in all cases

**Comment by aphillips** [comment]
Fixed
