### ISSUE TITLE
[css-counter-styles] Classification for 'cjk-earthly-branch' and 'cjk-heavenly-stem' #2096

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#547]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/2096

**Comment by xfq** [comment]
CSSWG issue closed.

New spec text: https://drafts.csswg.org/css-counter-styles-3/#simple-fixed
