### ISSUE TITLE
[css-text-decor] Characters to skip for emphasis marks (text-emphasis) #839

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#552]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

https://github.com/w3c/csswg-drafts/issues/839

**Comment by xfq** [comment]
This issue seems to be the same issue as #530.

**Comment by r12a** [comment]
You're right. Thanks @xfq .
