### ISSUE TITLE
[css-text-4] Propose 'text-spacing: space-first' (trim-start-except-first-line) as a normal behavior #2462

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#553]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/2462

**Comment by xfq** [comment]
Issue closed accepted by CSSWG resolution.

Current spec text: https://www.w3.org/TR/css-text-4/#text-spacing-trim-property
