### ISSUE TITLE
[css-text-4] Allow for paragraph-level line breaking #672

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#556]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/672

**Comment by himorin** [comment]
Change made to add 'stable' and 'pretty' to text-wrap in addition to 'wrap', 'nowrap' and 'balance'
PR: https://github.com/w3c/csswg-drafts/commit/2a5b5e466a2f69c7c649e9ec813899c560208e6c

**Comment by r12a** [comment]
This is for level 4.  I think we need to consider this carefully before closing (and it's a long thread).  So i'm going to remove the close label for now, and leave the needs-attention label in place.

**Comment by r12a** [comment]
I finally fought my way through the thread.  I think it's ok to close this.  (There may be i18n issues to consider, but i'm not sure we can easily guess what they'll be in advance.)
