### ISSUE TITLE
language properties don't reference BCP47 or 639-3

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#558]
6.3.5 Property: language (etc.)
https://w3c.github.io/dxwg/dcat/#Property:catalog_language

> Resources defined by the Library of Congress (1, 2) SHOULD be used.
> If a ISO 639-1 (two-letter) code is defined for language, then its corresponding IRI SHOULD be used; if > no ISO 639-1 code is defined, then IRI corresponding to the ISO 639-2 (three-letter) code SHOULD be > used.

The `language` property of several items in this document have the above reference, which is presumed to related to Dublin Core's definition of language. This doesn't allow for full language tags, which are frequently useful in identifying language. It also doesn't allow for ISO 639-3 codes. 

I suspect the problem here, once again, is lack of an IRI reference for BCP47 tags. If that's the case, should someone propose an URN for BCP47? Or do we go to CLDR for help? In any case, this seems a gap that could easily be filled.

---
**WHEN CREATING A NEW ISSUE DO SO ABOVE THIS PARAGRAPH, REPLACING THE PROMPTS, BUT LEAVE THIS PARAGRAPH INTACT AS WELL AS THE TEXT BELOW IT** When this issue is raised in the github/bugzilla/mail of the WG that owns the spec, use the text above this para as the basis for that comment. Then edit this issue to remove this paragraph and ALL THE TEXT ABOVE IT. Replace the text 'link_to_issue_raised' below with a link to the place you raised the issue, but leave the remaining text below this para unaltered.

**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

link_to_issue_raised

**Comment by r12a** [comment]
Not sent. Closed in favour of https://github.com/w3c/i18n-activity/issues/709
