### ISSUE TITLE
[css-text] Clarify what ligatures are optional #2644 

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#565]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/2644

**Comment by himorin** [comment]
change made, [modified text in "More precisely define interaction of letter-spacing and ligature font features."](https://github.com/w3c/csswg-drafts/commit/caf1e4747f2bd906bb9f671af8c463b28b97deda) and [csswg-drafts PR #3430](https://github.com/w3c/csswg-drafts/pull/3430).

**Comment by r12a** [comment]
It may be closable, but i'd like to read it in some more detail before we close our tracker.
