### ISSUE TITLE
Fix #593 - Refer to RFC 8266 for RP-controlled UI strings #878

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#567]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/webauthn/pull/878

**Comment by himorin** [comment]
Changes made, based on RFC #8264-8266, PR: https://github.com/w3c/webauthn/pull/951
also this is PR for issue tracked by https://github.com/w3c/i18n-activity/issues/208
