### ISSUE TITLE
Gamepad API > 2018-06-27

### ISSUE THREAD

**Issue by LJWatson** [w3c/i18n-activity#569]
We would welcome your review of the [Gamepad API specification](https://www.w3.org/TR/2018/WD-gamepad-20180508/), as part of our wide review before transitioning to Candidate recommendation (CR).

If there are any issues arising from your review, please file them on the [Gamepad GitHub repo](https://github.com/w3c/gamepad), and apply the "wide review" and "i18n" labels to each issue. This will help us track your comments and respond accordingly.

If there are no issues arising from your review, please let us know by reply to this thread.

We would appreciate your comments no later than Friday 27th June 2018. Thank you.

**Comment by r12a** [comment]
I read through this spec but didn't find anything needing a mention wrt i18n. Time stamps are used, but they don't appear to be locale-sensitive.

@LJWatson I recommend that you, or perhaps better one of the editors, run through the self-review checklist at https://www.w3.org/International/techniques/developing-specs to see whether you spot anything relevant.

**Comment by xfq** [comment]
I also read through this spec today, and didn't find anything i18n-wise.

**Comment by aphillips** [comment]
Hello @LJWatson and Gamepad,

This is to let you know that we did not find any issues. I am closing this tracking item and moving your spec to "review completed" in our radar.

[I18N-ACTION-719]
