### ISSUE TITLE
Standardizing on IDNA 2003 in the URL Standard

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#57]
http://lists.w3.org/Archives/Public/public-iri/2013Aug/0000.html
## 

Raised by:Richard Ishida
Opened on:2013-08-20

By: Anne van Kesteren

[[
http://lists.w3.org/Archives/Public/www-archive/2013Aug/0008.html
might be of interest to readers of these lists.
]]

Here are the contents of that email:

[[
Hey hey,

So one part that's missing in http://url.spec.whatwg.org/ is domain
names. As far as I can tell no browser has moved beyond IDNA 2003
(Opera "regressed" when it adopted Chromium) other than updating their
Unicode implementation and nobody is interested in implementing IDNA
2008 (whatever that means, it doesn't exactly define it all the way
from code points in an unparsed URL to host bytes).

Given that, my plan is to put that in the specification. IDNA 2003,
its label separators, the Unicode normalization it uses (but without
restrictions to a particular Unicode version), ...

Some registrars have moved to IDNA 2008, but this creates security
issues as pointed out in http://unicode.org/reports/tr46/ and people
are unlikely to register names that do not work. I suspect long term
the IETF will have to revisit this, but in the mean time it would be
good to have accurate documentation for how we want everything around
URLs to work.

If there's anything I'm missing here, I'd love to hear about it. If
you want more background reading, I wrote this after doing some
research last year: http://annevankesteren.nl/2012/11/idna-hell

Kind regards,
]]

**Comment by duerst** [comment]
http://annevankesteren.nl/2012/11/idna-hell says: "IDNA2003 with updated Unicode maps ß to ss" and "IDNA2003 with an updated version of Unicode (ß becomes ss)". I'm not sure Anne intended this, but it gives the impression that the original IDNA2003 did not map ß to ss. Such an impression would be false; ß is in Unicode from the start and was always mapped that way in IDNA2003.

**Comment by duerst** [comment]
Looking at this again, the mail from Anne is from 2013, and his post is from 2012, and Richard started this issue in 2016. Can anybody explain why this is coming up now?

**Comment by r12a** [comment]
@duerst Katy has begun trawling through old issue tracker items that we haven't yet closed, with a view to closing them or doing something contructive. This issue may well be stale. I'm going to take a look at it now...

**Comment by r12a** [comment]
I think this issue is stale and should be closed in favour of a review of the latest URL spec (https://url.spec.whatwg.org/).

**Comment by KatyMawhood** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2019/04/11-i18n-minutes.html).

- Closed #57
<details><summary><i class="differentiate">View the transcript</i></summary>
&lt;Katy> <a href="https://github.com/w3c/i18n-activity/issues/57">https://github.com/w3c/i18n-activity/issues/57</a><br/>
close<br/>
</details>
