### ISSUE TITLE
 Mark ruby with rb rb* rt rt* at risk? #1424 

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#570]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/html/issues/1424

**Comment by himorin** [comment]
there is a difference in state between w3c/html and whatwg/html on ruby related elements, and tracked issue of this is targeting w3c/html. so, we'd be possible to close this issue since background condition differs to the living one.

**Comment by r12a** [comment]
I think we need to establish a list of related issues already raised against the WhatWG spec and compare with this before closing.  At the last TPAC Chaals took an action to propose that WhatWG spec be updated to match W3C spec for ruby, including rb and rtc tags.  Nothing has yet happened.  We should spin up a project to move this forward once the string-meta topic has reduced in intensity.  In the meantime, i recommend to keep this tracker item open.

**Comment by r12a** [comment]
Agreed to close during telecon, since this is a W3C issue that appears to no longer be relevant.
