### ISSUE TITLE
 Default styling for q element #3636 

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#571]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/whatwg/html/issues/3636

**Comment by xfq** [comment]
HTML issue closed by removing the UA rendering section.

**Comment by r12a** [comment]
I think we should close this, and move our attention to https://github.com/w3c/csswg-drafts/issues/5478

**Comment by himorin** [comment]
This is an issue for PR https://github.com/whatwg/html/pull/5868 (https://github.com/w3c/i18n-activity/issues/970  in this tracker), and fixed.
Closing this tracker (agreed during [weekly call](https://www.w3.org/2021/01/28-i18n-minutes.html#t06)).
