### ISSUE TITLE
 Require UTF-8 #1039 

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#574]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/html/issues/1039

**Comment by himorin** [comment]
Change made, make accept-charset only to 'utf-8'.
https://github.com/whatwg/html/pull/4195

**Comment by himorin** [comment]
Change made, made legacy encoding information reinstated (editorial change).
https://github.com/w3c/html/pull/1504

**Comment by himorin** [comment]
change had made also in https://github.com/whatwg/html/pull/3091
