### ISSUE TITLE
i18n-ISSUE-402: Broken copy/paste behavior with IRIs

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#58]
Raised by:Dennis Tan Tanaka
Opened on:2014-12-22

While exploring the new service from CNNIC/Coremail (http://中文邮箱.网络) I came across the following behavior when copying/pasting the IRI onto other applications.

Test 1: Windows PC (Windows 7 Enterprise, SP 1) using Chrome 39
- The IRI maintains its U-Label form and resolves the site with no problem. No issues here.
- When trying to copy/paste the IRI (from Chrome's address bar) into other application (e.g. Google Docs, MS Excel, MS PowerPoint) the IRI is pasted in its A-Label form (i.e. http://xn--fiq228cmvpbgt.xn--io0a7i/)
- The pasted IRI is recognized as a link.
  = Result: broken user experience
  = Expected result: IRI should keep its U-Label form

Test 2: Windows PC (Windows 7 Enterprise, SP 1) using IE 8
- The IRI resolves to the site with no issues and the IRI keeps its U-label form. No issues here either.
- When copying/pasting the IRI from IE to other applications the IRI maintains its U-Label form, however it is not recognized as a link (even thought it is pasted with the http:// prefix)
  = Expected result: IRI should be recognized as a link

Test 3: iOS 8 (iphone) using Safari
- Pretty much the same behavior as in Win/IE test. The IRI maintains its U-Label form across applications.
- The IRI is recognized as a link in some application I tested with. It was recognized as as link in Notes, but it was not recognized as a link in Mail or Gmail for iOS.
  = Expected result: Consistent behavior across applications

These three test cases might not be as extensive as they should be but I think there is something funny about how Chrome is encoding the URL in the copy/paste operation. Can anyone shed some light into this? Thanks!

**Comment by aphillips** [comment]
closing as stale in 2016-07-21 telecon
