### ISSUE TITLE
many fields such as `statusReason` have no lang/dir support

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#580]
https://github.com/w3c/vc-data-model/issues/436

**Comment by r12a** [comment]
Actually a number of fields contain natural language text, throughout the document.

**Comment by msporny** [comment]
We've added a section on "Internationalization Considerations" in https://github.com/w3c/vc-data-model/commit/1cadfb11f2c9e7ed09dcba7cde3fe2c9d1b41f77. Please let us know if that addresses this issue. If not, we could try to elaborate much more in the Implementation Guidance notes.

**Comment by himorin** [comment]
note, PR is https://github.com/w3c/vc-data-model/pull/641, in collaboration with i18n WG
