### ISSUE TITLE
systemLanguage is not clear about case-insensitive matches

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#587]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/svgwg/issues/517

**Comment by r12a** [comment]
This was closed this week. I hadn't noticed it earlier. We should check it out.

**Comment by xfq** [comment]
Changes to the spec: https://github.com/w3c/svgwg/commit/4595f3527f71fe10420af55941b2303c28ac1418

**Comment by xfq** [comment]
Closing per https://www.w3.org/2022/03/31-i18n-minutes.html#t09
