### ISSUE TITLE
Add over-most-under-last value to ruby-position & text-emphasis-position for captioning

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#588]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/2998

**Comment by himorin** [comment]
Closed: specs updated via https://github.com/w3c/csswg-drafts/commit/d6f260e24ba7d1b8ef48e0941e77dce862a5a149 and https://github.com/w3c/csswg-drafts/commit/fcb8ef04220fa3d464d91d670ff7f1b8e7a65fcc to allow ruby-position to apply to ::first-line. Also followup issue raised as https://github.com/w3c/csswg-drafts/issues/4642 .
