### ISSUE TITLE
truncation to 64-byte upper limit doesn't mention character boundaries

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#589]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/webauthn/issues/973

**Comment by himorin** [comment]
Editorial change has made at https://github.com/w3c/webauthn/pull/1205

**Comment by aphillips** [comment]
satisfied
