### ISSUE TITLE
highly detailed text in video content

### ISSUE THREAD

**Issue by stpeter** [w3c/i18n-activity#599]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/mst-content-hint/issues/35

**Comment by r12a** [comment]
The document is still a WD. The text is still there. Should we send this?

**Comment by aphillips** [comment]
This was missing the tracker/needs-resolution labeling. I added tracker manually and am adding it to the agenda to discuss in our next telecon (or perhaps friday at TPAC)

**Comment by aphillips** [comment]
Fixed
