### ISSUE TITLE
i18n-ISSUE-404: Lang matching undefined

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#60]
Raised by:Addison Phillips
Opened on:2015-01-07

http://w3ctag.github.io/packaging-on-the-web/#fragment-identifiers

In section 3.4, there is this text about the 'lang' identifier:

> If the lang parameter is specified, the candidate parts are further filtered down to only those that have a Content-Language header whose media type matches the language tag provided by the lang parameter. 

What "matches" means is undefined. An exact match may not be appropriate? See RFC 4647 in BCP 47 for more details.

There also is no example provided and probably there should be one. For those reading only this Issue, the "Content-Language header" mentioned is part of the file format. 

The idea of language negotiation using fragments probably should be considered here. You might have a fragment with "lang=en" and several parts:

Content-Language: en-US
...
Content-Language: en-GB
...
Content-Language: en-AU
...

Are any or all selected? Should the fragment Id be expected to be more explicit (using Lookup style matching)?

**Comment by blackberryOS** [comment]
https://github.com/w3c/i18n-activity/issues/60

**Comment by xfq** [comment]
Since the Packaging on the Web document is [obsolete](https://github.com/w3ctag/packaging-on-the-web#note-that-this-repository-is-obsolete) now, can we close #59 and #60?

**Comment by r12a** [comment]
The obsoletion page says:

> Please consult the [WICG WebPackage](https://github.com/WICG/webpackage) repository for continuing work on this subject.

It's not clear to me whether that is different work (to which our comment may apply) or not.

**Comment by r12a** [comment]
Agreed during telecon to close as stale.
