### ISSUE TITLE
css-text-3 line-break property is not CJK-specific

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#603]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/1252

**Comment by himorin** [comment]
Change made, modified editional note in [PR csswg-drafts #3420](https://github.com/w3c/csswg-drafts/pull/3420)

**Comment by r12a** [comment]
Editorial change. I agree to close.
