### ISSUE TITLE
css-text-4 hyphenate-character doesn't accept just a character

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#604]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/2809

**Comment by himorin** [comment]
Change (https://github.com/w3c/csswg-drafts/commit/ad3f54942bef956278ffff65db1737d31ee8b065) made to allow user agent to a limited number of typographic character units.
