### ISSUE TITLE
[clreq] Starter text for sections on text decoration, emphasis, etc #192

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#608]
This is a tracker issue. Only discuss things here if they are i18n WG internal meta-discussions about the issue. Contribute to the actual discussion at the following link:

§ [w3c/clreq#192](https://github.com/w3c/clreq/issues/192)

**Comment by r12a** [comment]
Closing this tracker item, since the issue pointed to is neither a spec issue, nor a question for the lreq group. (It's an editorial suggestion.)
