### ISSUE TITLE
[whatwg/html] It is unclear how directionality should be inherited into Shadow DOM #3699

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#609]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/whatwg/html/issues/3699

**Comment by aphillips** [comment]
parent issue is closed after a discussion thread with hundreds of entries and many commits. I don't see a reason to keep this open.
