### ISSUE TITLE
i18n-ISSUE-397: Interaction of variation selectors and proposed emoji modifiers

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#61]
https://www.w3.org/Mail/flatten/index?subject=I18N-ISSUE-397&list=public-i18n-core
## 

Raised by:Addison Phillips
Opened on:2014-12-11

http://www.unicode.org/draft/reports/tr51/tr51.html

I can't find any mention about how variation selectors and emoji modifiers interact (canonical order, etc.).

**Comment by aphillips** [comment]
obsolete.

Please note that this comment was passed to Unicode.
