### ISSUE TITLE
[csswg-drafts] [css-logical] Flow-relative syntax for `margin`-like shorthands #1282

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#611]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/1282

**Comment by r12a** [comment]
Closing this, since it's a duplicate of https://github.com/w3c/i18n-activity/issues/586
