### ISSUE TITLE
update website (gh-pages/i18n-wg/index.html) for FTF meeting

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#613]
current version of i18n-activity web site lists next FTF meeting as TPAC 2017.
[code](https://github.com/w3c/i18n-activity/blob/gh-pages/i18n-wg/index.html) and [site](http://w3c.github.io/i18n-activity/i18n-wg/)

better to move 2017 and 2018 into a list of past FTF.

**Comment by r12a** [comment]
Thanks for noticing that @himorin. Would you like to try fixing it yourself? Seems like a nice simple way to get some experience :-)

**Comment by himorin** [comment]
ah, yes, I will (try to) push PR. (actually I filed somehow as a reminder to myself...)
