### ISSUE TITLE
[css-text] Cursive shaping breaks (near an image representing a letter)

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#629]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/3487

**Comment by himorin** [comment]
Summary: Define behavior on cursive shaping with or without zwj when character is replaced by emoji or equivalent img element?
Close: Implementation bug. Markup should have no effect on joining behavior and this should be handled by using zwj.

**Comment by aphillips** [comment]
we indicated satisfaction with the fix, so closing
