### ISSUE TITLE
[css-text-3] Implement or unship word-break:break-word

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#637]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/2390

**Comment by r12a** [comment]
Added link rather than the text that was there, which seemed spurious.

**Comment by himorin** [comment]
change made, "word-break:break-word" added
https://github.com/w3c/csswg-drafts/commit/8067e5c10acc1f29e453e3cdf96c40cf7c0e8bc1
