### ISSUE TITLE
Have fields for locale-specific information (names, addresses, etc.) been checked?

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#640]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/vc-data-model/issues/734

**Comment by r12a** [comment]
The spec is now a Rec.  Which course of action should we take?
1. just close it
2. close with recycle label
3. send

**Comment by aphillips** [comment]
editorial change looks good; issue was closed; this is an old issue.
