### ISSUE TITLE
Example uses a timestamp for what should just be a (floating) date value

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#650]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/vc-data-model/issues/733

**Comment by r12a** [comment]
The spec is now a Rec.  Which course of action should we take?
1. just close it
2. close with recycle label
3. send

**Comment by xfq** [comment]
I think this spec is still being maintained by the new [VCWG](https://www.w3.org/2020/01/vc-wg-charter.html). If we think this issue is important enough, we can still raise it and they can add it to the errata or even publish an Edited Recommendation.

**Comment by aphillips** [comment]
fixed
