### ISSUE TITLE
Richer negotiation re: address redaction?

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#651]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/payment-request/issues/842

**Comment by himorin** [comment]
moved to more suitable target https://github.com/w3c/payment-method-basic-card/issues/72
close? or repoint tracker?

**Comment by ianbjacobs** [comment]
Addresses are no longer part of Payment Request API. Please close. Thank you.
