### ISSUE TITLE
Mention the use of U+2500 box drawing character for bracket?

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#654]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/clreq/issues/205

**Comment by himorin** [comment]
closed with mention that U+2E3A or double U+2014 are recommended.

**Comment by r12a** [comment]
Sounds like the right answer to me. I propose we close this tracker.
