### ISSUE TITLE
[css-text] Add new CSS text-transform values for math

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#659]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/3745

**Comment by xfq** [comment]
CSSWG issue closed in favor of https://github.com/w3c/csswg-drafts/issues/5386
