### ISSUE TITLE
DPub BG & i18n concerns

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#664]
_Originally posted by @iherman in https://github.com/w3c/i18n-activity/issues/196#issuecomment-479418947_

... I think the overall topic (not necessary reduced to the issue of pagination) could (should?) be taken up by the Business Group.

There is a spreadsheet:

https://docs.google.com/spreadsheets/d/1kq5zOMzOxvHkM8yAgoqao0M0-z5FBzqtWWoO9qLS8PM

that colllects topics that the BG plans to get into. The group is, currently, and a phase of collecting ideas. Maybe the i18n group should add an entry about what exactly you would welcome to see; the BG may pick that topic up. 

@liisamk @w3c/hcls-drug-drug-interaction-editors

**Comment by r12a** [comment]
@iherman how do we add things to that list?  Do we just edit the spreadsheet directly?
And do you have a link to the BG charter/homepage?

**Comment by iherman** [comment]
> @iherman how do we add things to that list? Do we just edit the spreadsheet directly?
And do you have a link to the BG charter/homepage?

I think it is all right if you add a record in the spreadsheet directly.

* Official charter/homepage: https://www.w3.org/community/publishingbg/
* "work page" (with, eg, links to minutes): https://w3c.github.io/publ-bg/

**Comment by laudrain** [comment]
@r12a it is ok if you edit that document directly. Thanks

**Comment by r12a** [comment]
Done, at the bottom of the page.

**Comment by r12a** [comment]
I think this is stale. I support @xfq proposal to close.
