### ISSUE TITLE
[css-text] text-transform's design, intent and reality resolution

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#667]
People (esp. wai) arguing whether, if you copy text with text-transform applied, should you see the in-memory characters, or the visual representation when you paste it. Are there other operations that should produce that result?

**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/3775

**Comment by r12a** [comment]
I propose that we close this, since i think the edits made support the i18n position.
