### ISSUE TITLE
[css-scroll-snap-1] Clarify which writing-mode is used for scroll-snap-align, scroll container or snap position element?

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#668]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/3815

**Comment by aphillips** [comment]
A fix was landed. `advice-requested` was responded to in the past
