### ISSUE TITLE
(editorial) content type examples may be misleading

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#678]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/wot-thing-description/issues/636

**Comment by r12a** [comment]
Spec changed to read "'text/plain') and potential parameters (e.g., 'charset=utf-8') for the media type." I agree we should close.

**Comment by himorin** [comment]
note, change was https://github.com/w3c/wot-thing-description/commit/3c3c7f745aef7731b8af6b201dc2375c4fcf3eac
