### ISSUE TITLE
i18n-ISSUE-414: No means of obtaining correctly localized manifest

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#69]
§ https://github.com/w3c/manifest/issues/336
## 

Raised by:Addison Phillips
Opened on:2015-02-23

http://www.w3.org/TR/2015/WD-appmanifest-20150212/#obtaining

Section 6.1 discusses the steps in obtaining a manifest. There is no discussion of obtaining a correctly localized reference, particularly for use in cases where the source page itself has used language negotiation.

**Comment by marcoscaceres** [comment]
Related issue on our side: https://github.com/w3c/manifest/issues/338

**Comment by himorin** [comment]
In addition to lang member was added to WebAppManifest, text for choosing language in a phase of requesting manifest was added by PR #434 as appendix.
https://github.com/w3c/manifest/commit/cbd8343df1ea4bb1c29abc6a1804954159e0737a

Closing this tracker. (agreed during [weekly call](https://www.w3.org/2021/01/28-i18n-minutes.html#t06))
