### ISSUE TITLE
i18n-ISSUE-428: 4.3.2 emphasis spans

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#7]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=28262
§ https://github.com/w3c/webvtt/issues/228
## 

Raised by:Addison Phillips
Opened on:2015-02-26

4.3.2 WebVTT cue text
http://www.w3.org/TR/webvtt1/#webvtt-cue-text

A variety of spanning mechanisms, such as bold, italic, and underline are provided. Some languages use different emphasis forms. Should these emphasis types also be provided?

We advise against presentational markup of this kind, since it isn't interoperable across writing systems and may cause unnecessary problems for localization. (The HTML5 specification has also proposed that these tags should be used more along semantic lines.) In the HTML case, there was a legacy issue, but here we don't see one, and recommend instead that styling be used to determine the presentation of the text.

For some of the issues associated with `<b>` and `<i>` tags, see http://www.w3.org/International/questions/qa-b-and-i-tags

**Comment by r12a** [comment]
This was rejected. We need to check the arguments.
Richard Ishida, 23 Jul 2015, 11:26:38

**Comment by r12a** [comment]
test

**Comment by himorin** [comment]
After moving to github https://github.com/w3c/webvtt/issues/228, PR https://github.com/w3c/webvtt/pull/267 as made to change state to satisfy this.

**Comment by r12a** [comment]
I'm closing this because i think it's resolved.
