### ISSUE TITLE
i18n-ISSUE-415: No language metadata for 'name'

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#70]
§ https://github.com/w3c/manifest/issues/335
## 

Raised by:Addison Phillips
Opened on:2015-02-23

http://www.w3.org/TR/2015/WD-appmanifest-20150212/#name-member

The 'name' manifest member does not provide a way to indicate the language of the string. This may be necessary for proper presentation/rendering of the name, since, for example, different fonts might be selected for different languages (such as when selecting between Japanese and Chinese).

**Comment by marcoscaceres** [comment]
See https://w3c.github.io/manifest/#lang-member

**Comment by himorin** [comment]
WebAppManifest was updated to include TextDirectionType dir (ltr, rtl, auto).
Closing this tracker (agreed during [weekly call](https://www.w3.org/2021/01/28-i18n-minutes.html#t06)).
