### ISSUE TITLE
Do we need directional metadata in the first place ?

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#706]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/rdf-dir-literal/issues/7
On best practices for use cases of directional metadata

**Comment by r12a** [comment]
The repository has been archived, and i believe the thread came to a useful conclusion, so i'm closing this.
