### ISSUE TITLE
[css-text] For most languages, hyphens:auto should not hyphenate Capitalized words

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#707]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/3927

Whether to add a note to suggest not hyphenate capitalized words in places where hyphens:auto is specified.

**Comment by xfq** [comment]
CSS issue closed. A note was added to the spec: https://github.com/w3c/csswg-drafts/commit/87b27492a11b003c488951fc9cfa76d70f7492fc
