### ISSUE TITLE
[css-text-4] hyphenate-character doesn't just put hyphen at end of line

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#708]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/2975
On place of hyphenate character handled by hyphenate-character property to extend from just the end of line

**Comment by aphillips** [comment]
fixed
