### ISSUE TITLE
references to ISO-639 vs. BCP47

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#709]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/dx-dcat/issues/287

**Comment by xfq** [comment]
WG issue closed.

Current spec text: https://w3c.github.io/dxwg/dcat/#Property:resource_language
