### ISSUE TITLE
[css-text] Clarify whether soft breaks exist at boundaries of an inline element with `word-break:break-all`

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-activity#713]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/3897

**Comment by himorin** [comment]
rough summary:
  To make spec states clear on edge cases of an inline element with `word-break:break-all`.
  Three possibilities to be taken are pointed in https://github.com/w3c/csswg-drafts/issues/3897#issuecomment-505931859

**Comment by himorin** [comment]
closed with resolved to keep breaking Rules at inline element boundaries as undefined
