### ISSUE TITLE
[css-text-decor] Limits on text-underline-offset to preserve semantic meaning

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-activity#714]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/4059

**Comment by himorin** [comment]
WG agreed to resolve this issue with no change on spec state and no limit on text-underline-offset.
