### ISSUE TITLE
i18n-ISSUE-417: appropriate use of ACI

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#72]
§ http://www.w3.org/Mail/flatten/index?subject=i18n-ISSUE-417&list=public-webapps
## 

Raised by:Addison Phillips
Opened on:2015-02-23

http://www.w3.org/TR/2015/WD-appmanifest-20150212/#sizes-member

In section 8.3 there are instructions for comparing/extracting size values that are either the string 'any' or in the format wwwxyyy (e.g. 1024x768). This section refers to ASCII case-insensitive comparison in an appropriate way. This comment is to call out the appropriate usage in this case.

**Comment by marcoscaceres** [comment]
:heart:

**Comment by r12a** [comment]
Addison: "Obviously, no action is required on this comment".  We should therefore close.

**Comment by r12a** [comment]
Agreed to close during telecon.
