### ISSUE TITLE
https://w3c.github.io/i18n-activity/guidelines/editing doesn't seem to work

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-activity#723]
The style doesn't seem to load correctly:

![Screenshot_2019-07-29 Editorial guidelines for i18n docs](https://user-images.githubusercontent.com/2863444/62024945-3ed35d80-b209-11e9-8f50-304e2fbe4696.png)

* * *

/cc @r12a

**Comment by r12a** [comment]
Thanks for the heads up.  Should be fixed now.
