### ISSUE TITLE
i18n-ISSUE-433: (editorial nit) spec title

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#73]
Raised by:Addison Phillips
Opened on:2015-02-26

http://www.w3.org/TR/2015/WD-appmanifest-20150212/

The title of the specification is "Manifest for web application". Should this be "Manifest for a Web application"?

**Comment by marcoscaceres** [comment]
Note that it's now just "Web App Manifest". See latest editor's draft... so you can probably close this.

**Comment by aphillips** [comment]
LGTM
