### ISSUE TITLE
Pub Manifest self review

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#739]
Ivan has requested that we check this.

§ https://github.com/w3c/pub-manifest/issues/38

This should use the wpub label, since it was previously a document in that repo.

**Comment by xfq** [comment]
I reviewed this spec today.

The only issue I see (besides an [editorial issue](https://github.com/w3c/pub-manifest/issues/46)) is about base direction in strings, although that's a JSON-LD issue.

**Comment by himorin** [comment]
i18n HR agreed that all review comments have been addressed to our satisfaction
