### ISSUE TITLE
i18n-ISSUE-456: 2.1.1 provide a terminology section? [non-I18N]

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#74]
Raised by:Addison Phillips
Opened on:2015-04-01

http://www.w3.org/TR/dpub-annotation-uc/

Section 2.1.1. There is a parenthetical note: "henceforth user-agent". 

Perhaps create a terminology section to avoid embedded terminology references. This makes it easier to manage and maintain specialized jargon.

**Comment by aphillips** [comment]
obsolete comment
