### ISSUE TITLE
[css-ruby] Incorrect language tags in the source file?

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#741]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/3292

incorrect lang tags are used in glossary section of css-ruby spec

**Comment by xfq** [comment]
CSSWG issue closed.

The language tags for the English words (in other words, romanization of CJK words) have been removed, and terms in the original languages have been added: https://github.com/w3c/csswg-drafts/commit/f01e4d3c6f757da3eb013b51acccd08ab375e721
