### ISSUE TITLE
[css-text] All IN characters?

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#747]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/2447
Rewording state of line-break property to make definitions on inseparable characters clearer

**Comment by r12a** [comment]
Closing this since the v small editorial change i requested has been made.
