### ISSUE TITLE
text-spacing is very complicated

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#755]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/4246
To identify unnecessary combinations out of 769 combinations of text-spacing.

**Comment by aphillips** [comment]
Possibly the best-titled issue in history, the underlying issue is now closed with substantial edits done. Other issues remain here and there. Closing this tracker.
