### ISSUE TITLE
Introducing @dir (json-ld-syntax)

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#756]
Summary: Should JSON-LD2 introduce @dir to handle base direction?

**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/json-ld-syntax/issues/11

**Comment by himorin** [comment]
Closed as wontfix, new features should be compatible with the RDF data model, instead to have @dir.
