### ISSUE TITLE
Review of i18n self-review (Language related issues)

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#757]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/pub-manifest/issues/39

**Comment by himorin** [comment]
WG is looking into individual items on open issues and questions following [their self review](https://github.com/w3c/pub-manifest/issues/38) which is tracked by https://github.com/w3c/i18n-activity/issues/739 .

**Comment by r12a** [comment]
I18n WG moved this spec review to Completed in the radar, so closing.
