### ISSUE TITLE
[css-text-3] Allow breaking anywhere when dictionary is missing for SEA scripts

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#761]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/4284

Whether to allow to breaking anywhere instead of overflowing for words whose dictionary or morphological analysis is missing in UA.

**Comment by himorin** [comment]
Resolved as treat languages without known breaking rules as breakable anywhere similar to overflow:anywhere, rather than unbreakable, and change made by https://github.com/w3c/csswg-drafts/commit/0d78686ad39dd9b2e2e4ff1184f5686c8fd832d8

**Comment by aphillips** [comment]
fixed
