### ISSUE TITLE
[css-text-3] Define break at space to remove a space explicitly

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-activity#763]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/4308

**Comment by himorin** [comment]
Short summary: define handling of collapsible spaces on the line-break opportunity in bidi boundary

**Comment by himorin** [comment]
Spec changed to remove space before a line break even if reordered to the middle of line by bidi reordering
https://github.com/w3c/csswg-drafts/commit/44236e2480ffbbbebd8bea3ccfdfabe121ca1337

**Comment by r12a** [comment]
I support closing this tracker item.
