### ISSUE TITLE
Text base direction again — but now with a solution:-)

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#764]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/pub-manifest/issues/75
Update with including `@direction` to JSON-LD 1.1, for base direction of text

**Comment by himorin** [comment]
PR (https://github.com/w3c/pub-manifest/pull/92) merged to add text base direction.

**Comment by r12a** [comment]
+1 to close

The WG issue is closed.
