### ISSUE TITLE
[css-text-decor] Consider adding an `all` value to `text-decoration-skip-ink`

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-activity#771]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/4277

**Comment by himorin** [comment]
Short summary: Add all to text-decoration-skip-ink to make it possible to enable skip-ink behavior on CJK text for e.g. calligraphic font.

**Comment by xfq** [comment]
CSSWG issue closed. `text-decoration-skip-ink: all` has been added.

Current spec text: https://drafts.csswg.org/css-text-decor-4/#valdef-text-decoration-skip-ink-all

**Comment by aphillips** [comment]
fixed
