### ISSUE TITLE
textarea[maxlength] interoperability issue

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-activity#772]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/whatwg/html/issues/1467

**Comment by himorin** [comment]
short summary: character counting for textarea[maxlength] differs among implementations on like non-BMP, combining, etc.

**Comment by aphillips** [comment]
fixed
