### ISSUE TITLE
Add informative note to tts:fontStyle recommending use of tts:shear instead of tts:fontStyle="italic" for Japanese text.

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#775]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/imsc/issues/495

to add a note to recommend that the content author specify tts:shear on Japanese text instead of tts:fontStyle="italic". (following note in CSS font-style for italic fallback

**Comment by xfq** [comment]
Non-normative added in PR https://github.com/w3c/imsc/pull/514

New spec text: https://w3c.github.io/imsc/imsc1/spec/ttml-ww-profiles.html#text-italic-shear-oblique
