### ISSUE TITLE
Devices and Sensors Reviews (4 docs) > 2019-11-14

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#780]
The Devices and Sensors Working Group requests wide review of the following specs. The only substantial change since the last CR is the the addition of WebDriver extensions. Please provide your feedback by 2019-11-14.

WebDriver API and its extensions enable test automation and are not web-exposed in a normal browsing scenario. The extensions in scope of this review request are defined in the following Automation sections:

   Generic Sensor API
   https://w3c.github.io/sensors/#automation

   Accelerometer
   https://w3c.github.io/accelerometer/#automation
   
   Gyroscope
   https://w3c.github.io/gyroscope/#automation

   Orientation Sensor
   https://w3c.github.io/orientation-sensor/#automation

The group requests feedback via the respective specifications' GitHub repositories, or via email to public-device-apis@w3.org.

The group is looking for confirmation that it has satisfied its relevant technical requirements and dependencies with other groups.

Thanks,

-Anssi (Devices and Sensors WG co-chair)

**Comment by himorin** [comment]
Check states of four specifications on automation sections, see **no** item relates to natural language, user input, date/time, nor cultural norms. All values are defined in SI units or normalized (by means of vector/matrix).

----
detail notes:

## Generic sensor

- No handling of natural language or user input
- This defines framework, mock sensors does not define return value syntax (nor unit), data formats are defined by each sensor specification
  - and each specification only defines its specific data format
- time related values are in Hz or DOMHighResTimeStamp, no dependency to TZ or cultural text

## Accelerometer

- Just a definition of data dictionaly
- Defines one dictionary (and two extensions) which has values with well defined SI unit

## Gyroscope

- Just a definition of data dictionaly
- Defines one dictionary which has values with well defined SI unit

## Orientation sensor

- Just a definition of data dictionaly
- Defines one dictionary (and one extention) which has quaternion of rotation matrix (normalized)
