### ISSUE TITLE
[css-fonts] Specify what generic font family maps to nastaliq

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#784]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/4397

Decide a way to explicitly specify which generic keyword means nastaliq

**Comment by aphillips** [comment]
generic(nastaliq) was added
