### ISSUE TITLE
[css-fonts] What does fangsong map to for non chinese text

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#785]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/4425

Define some guidance as to what sort of font it should map to for characters outside of Chinese, on fangsong.

**Comment by r12a** [comment]
@xfq what's happening here?  I saw a notification of a comment, but no longer see the comment here.  The `Close?` label doesn't appear to have been generated automatically when the WG issue was closed.
We don't normally remove it ourselves, as i remember, but i would expect the issue to be closed if we did.

**Comment by xfq** [comment]
Because I added the label incorrectly. I thought the issue was closed, but it was not.
