### ISSUE TITLE
[css-text-decor] Clarifying skip-ink:auto behavior in relation to CJK text

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#786]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/4276

To have clear state on skip-ink:auto behavior for CJK characters

**Comment by xfq** [comment]
CSSWG issue closed. A note on CJK scripts was added: https://github.com/w3c/csswg-drafts/pull/4737/files

A new issue on other non-CJK scripts will be filed.
