### ISSUE TITLE
[css-text] Line breaking for ambiguous characters; e.g., U+2010, U+2013

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#787]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/4419

Refine handling of U+2010 and U+2013 in link-break property from lang of writing-system to previous character.

/cc @kidayasuo

**Comment by xfq** [comment]
Adding `clreq` label since it affects Chinese as well.

Related discussions: https://www.w3.org/2019/11/07-clreq-minutes.html#x01

**Comment by himorin** [comment]
change made in https://github.com/w3c/csswg-drafts/commit/2cfcf436dde93692634bd8788bd163350be4f6d7, to 
- disallow before hyphen in normal and strict
- allow break between ID and hyphen in loose. This means Kanji+Hyphen breaks; and Alphabetic+Hyphen doesn't break, unless word-break: break-all makes Alphabetic behave like ID.
