### ISSUE TITLE
i18n-ISSUE-465: Human readable message not localizable?

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#79]
§ https://github.com/w3c/mediacapture-main/issues/673

-----

http://www.w3.org/Mail/flatten/index?subject=i18n-ISSUE-465&list=public-media-capture
## 

Raised by:Addison Phillips
Opened on:2015-04-24

http://www.w3.org/TR/2015/WD-mediacapture-streams-20150414/#widl-MediaStreamError-message

The 'message' value of MediaStreamError has no associate language or base direction information. Multiple 'message' values in different languages are not provided for. Since the message is generated by the user-agent, this may already be appropriately localized, but what about remote cases? And having the language and direction metadata may be useful when presenting the string in JS alerts or in an HTML context.

**Comment by xfq** [comment]
[Current text](https://w3c.github.io/mediacapture-main/#navigatorusermediaerrorcallback):

> A <code>MediaStreamError</code> object is either a <a href="https://heycam.github.io/webidl/#idl-DOMException">DOMException</a> object or an <a href="https://w3c.github.io/mediacapture-main/#overconstrainederror-constraint-message">OverconstrainedError</a> object.

Neither `DOMException` nor `OverconstrainedError` seems to have associate language or base direction information.

**Comment by xfq** [comment]
Related issue: https://github.com/w3c/i18n-activity/issues/842

**Comment by aphillips** [comment]
Created: https://github.com/w3c/mediacapture-main/issues/673
