### ISSUE TITLE
i18n-ISSUE-429: "valid" language tag

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#8]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=28263

§ https://github.com/w3c/webvtt/issues/217

**Comment by r12a** [comment]
Need to review and comment on suggestion for a banner.
Richard Ishida, 23 Jul 2015, 11:36:48

**Comment by himorin** [comment]
Change made to state valid BCP47 as well-formed checking on language tags by https://github.com/w3c/webvtt/pull/256
Asked for confirmation on change.

**Comment by r12a** [comment]
Telecon resolution: Keep open. Addison to reply. Needs further clarification about guidance.

**Comment by aphillips** [comment]
I did reply, but the issue is closed anyway. Should we raise the visibility?

**Comment by aphillips** [comment]
2024-05-23: we [discussed in telecon](https://www.w3.org/2024/05/23-i18n-irc#T14-27-14). Decided to close.
