### ISSUE TITLE
i18n-ISSUE-471: identify time zone dependent vs. independent cases

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#80]
https://www.w3.org/Mail/flatten/index?subject=I18N-ISSUE-471&list=public-webpayments-comments
## 

Raised by:Addison Phillips
Opened on:2015-05-15

http://www.w3.org/TR/web-payments-use-cases/

As a general observation, some of the use cases contain time-bound elements. These can be limits on things like refunds or payments, such as 6.3.4. which might be tied to a specific time zone (so that you know the specific end time local to a specific location--since "May 15, 2015" ends at different times in different places). Others may be zone independent. Care should be used to identify cases that have a time zone dependence. See also:

http://www.org/TR/timezones

**Comment by xfq** [comment]
The Web Commerce IG (successor of Web Payments IG) was closed. Should we close this issue?

**Comment by r12a** [comment]
Here's the request to retire the document: https://lists.w3.org/Archives/Team/webreq/2018Jul/0021.html

@ianbjacobs will follow up on the request to retire the doc. So +1 to close.
