### ISSUE TITLE
[css-fonts] Don't require browsers to always match every generic font family to a concrete font family

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-activity#804]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/4442

**Comment by himorin** [comment]
Short summary: To delete a state on forcing browsers to match at least one font face to every generic font family

**Comment by xfq** [comment]
CSSWG issue closed.
Resolved as serif, sanserif, and monospace must match, all other generics should match if appropriate.

Changes to the spec: https://github.com/w3c/csswg-drafts/commit/4443ab9a80153217732d0e33eaa9926390cf1fad
