### ISSUE TITLE
[css-text] Writing System prose is currently unimplementable on ICU

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-activity#805]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/4445

**Comment by himorin** [comment]
short summary: on behavior of ICU for handling of language which change behavior by sub-tag

**Comment by xfq** [comment]
CSSWG issue closed. Writing-system dependent adjustments to line breaking was marked "at risk": https://github.com/w3c/csswg-drafts/commit/f8659c968acc0c4e78ddce2db752142317c7b423
