### ISSUE TITLE
Flow-relative rootMargin

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-activity#806]
2.4. The IntersectionObserverInit dictionary
https://w3c.github.io/IntersectionObserver/#intersection-observer-init

> Similar to the CSS margin property, this is a string of 1-4 components, each either an absolute length or a percentage.

Currently, the `rootMargin` option only supports the "top, right, bottom, left" way of specifying margins, and flow-relative margins depending on the block flow direction and inline base direction are not supported. Flow-relative margins don't have a shorthand for now, tho. (See https://github.com/w3c/csswg-drafts/issues/1282)

---
**WHEN CREATING A NEW ISSUE DO SO ABOVE THIS PARAGRAPH, REPLACING THE PROMPTS, BUT LEAVE THIS PARAGRAPH INTACT AS WELL AS THE TEXT BELOW IT** When this issue is raised in the github/bugzilla/mail of the WG that owns the spec, use the text above this para as the basis for that comment. Then edit this issue to remove this paragraph and ALL THE TEXT ABOVE IT. Replace the text 'link_to_issue_raised' below with a link to the place you raised the issue, but leave the remaining text below this para unaltered.

**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ link_to_issue_raised

**Comment by xfq** [comment]
Ah, just found that there's a similar issue 2 years ago: https://github.com/w3c/i18n-activity/issues/488

Should I close this issue?

**Comment by r12a** [comment]
Agreed in telecon to close as duplicate.
