### ISSUE TITLE
[HTML] should it be called "case-sensitive"?

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#808]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/whatwg/html/issues/5067

**Comment by xfq** [comment]
WHATWG issue closed. The definition of string equality now uses 'is'/'identical to' from [Infra](https://infra.spec.whatwg.org/#string-is).

Commit: https://github.com/whatwg/html/commit/104104561103b135a7f03dfb4c7e76899e439325
