### ISSUE TITLE
[css-fonts] limit local fonts to those selected by users in browser settings (or other browser chrome)

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-activity#809]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/4497

**Comment by himorin** [comment]
Short summary: to prevent font based fingerpriting, ask browsers to load local fonts by opt-in from user basis

**Comment by aphillips** [comment]
replaced by https://github.com/w3c/csswg-drafts/issues/5421
