### ISSUE TITLE
i18n-ISSUE-472: geographic variation of terms or availability

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#81]
https://www.w3.org/Mail/flatten/index?subject=I18N-ISSUE-472&list=public-webpayments-comments
## 

Raised by:Addison Phillips
Opened on:2015-05-15

http://www.w3.org/TR/web-payments-use-cases/

I can't find any mention of geographic, country-of-residence, or other restriction on availability of an offer (maybe I missed it), or on the ability to redirect users to locally appropriate equivalent offers. Is this a gap?

There can also be specific T&Cs that apply differently based on the location of the user and provider of an offer (or of the third party payment system).

**Comment by xfq** [comment]
The Web Commerce IG (successor of Web Payments IG) was closed. Should we close this issue?

**Comment by r12a** [comment]
Here's the request to retire the document: https://lists.w3.org/Archives/Team/webreq/2018Jul/0021.html

@ianbjacobs will follow up on the request to retire the doc. So +1 to close.
