### ISSUE TITLE
[css-ruby-1] ruby overhang control

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#818]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/4492

Add property of limit to length of allowed overhang to before/after ruby base text.

**Comment by xfq** [comment]
CSSWG issue closed, and a new CSS property `ruby-overhang` was added.

Commit: https://github.com/w3c/csswg-drafts/commit/a3d09558c657c751e6f03372b401ffed1617971a

Spec text: https://drafts.csswg.org/css-ruby/#ruby-overhang
