### ISSUE TITLE
[css-text-3] treat all-neutral lines same as empty ones for plaintext alignment

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#819]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/4405

Start alignment side of all-neutral lines in `unicode-bidi: plaintext` block should be aligned to the containing box or not.

**Comment by xfq** [comment]
CSSWG issue closed.

Updated spec text: https://drafts.csswg.org/css-text-3/#bidi-linebox
