### ISSUE TITLE
i18n-ISSUE-476: International payment, taxation, delivery and trade restriction practices

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#82]
Raised by:Leandro Reis
Opened on:2015-06-02

Some web retailers sell physical goods to customers in different countries. As such, it would be helpful to mention some practices followed by such retailers when dealing with international customers: 

1) Payment : Provide a real-time currency converter mechanism, which lets buyer know approximately how much product will cost in their country's currency.

2) Taxation : Include amount of general sales or value-added tax imposed by the country where product is delivered to. For example, in the EU, standard VAT rates vary from 17% in Luxembourg to 27% in Hungary.

3) Delivery : Provide rates and estimated delivery times according to destination (which typically vary according to the distance from where goods are shipped from). For example, a U.K.-based retailer quotes delivery times of 1-15 business days for U.K., 3-18 business days for Continental Europe, and 7-23 days to the U.S and the rest of the World.

4) International trade restrictions : Provide overview of policies governing sales and delivery of goods to countries affected by international trade restrictions (e.g. the U.S. bans trade of goods with Iran, North Korea, Sudan, etc).

**Comment by aphillips** [comment]
close as stale
