### ISSUE TITLE
i18n-ISSUE-480: New role for Ruby?

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#83]
Raised by:Leandro Reis
Opened on:2015-07-30

Re: http://www.w3.org/TR/2015/WD-dpub-aria-1.0-20150707/#dpub-noteref

The dpub-noteref role deals with superscript text, which made me wonder if there should be a role for Ruby characters (and perhaps other international text layout features)? 

Thoughts?

Leandro

**Comment by aphillips** [comment]
close as stale
