### ISSUE TITLE
[css-ruby] Size and position of empty ruby level containers

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#833]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/4631

summary: To make state clarify on the case with an empty ruby base

**Comment by xfq** [comment]
CSSWG issue closed.

Empty ruby containers are now sized as if they have empty things in them: https://github.com/w3c/csswg-drafts/pull/4941/files

**Comment by aphillips** [comment]
fixed
