### ISSUE TITLE
[css-text-decor] Conflicting descriptions of `text-underline-position: left` or `right` in horizontal typographic mode

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#841]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/4656

short summary: Make editorial change to clarify on handling auto value

**Comment by xfq** [comment]
CSSWG issue closed. The caption has been updated to match the normative prose.

**Comment by aphillips** [comment]
fixed
