### ISSUE TITLE
Human readable error message without language info

### ISSUE THREAD

**Issue by bert-github** [w3c/i18n-activity#842]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/mediacapture-screen-share/issues/135

**Comment by aphillips** [comment]
🤷 

I18N was not satisfied by decisions like this one, but we gave a pass on them, so closing this tracking issue.
