### ISSUE TITLE
[css-fonts] The Cursive = Chinese Kaiti equivalent

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-activity#843]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/4606

**Comment by xfq** [comment]
Adding jlreq label as well (since 楷書体 is also used in Japan).

**Comment by himorin** [comment]
short summary: Chinese font Kaiti should be categorized as Cursive as https://www.w3.org/TR/css-fonts-4/#cursive-def

**Comment by xfq** [comment]
Kai is already categorized as cursive in CSS now (see [spec](https://www.w3.org/TR/css-fonts-4/#cursive-def) and [test](https://bobbytung.github.io/cursiveaskaifont/)). This issue is about whether that is correct.

**Comment by upsuper** [comment]
@xfq I think it's worth discussing in the next CLReq editor meeting.

cc @bobbytung

**Comment by xfq** [comment]
@upsuper OK. Will add it to the agenda.

**Comment by aphillips** [comment]
The parent issue is closed. w3c/clreq#587 may track this further. I'm going to close this, but @xfq should reopen if we're not satisfied.
