### ISSUE TITLE
Providing alternative breaking behaviours for Ethiopic

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#845]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/4765

**Comment by himorin** [comment]
short summary: how can an Ethiopic author can apply the different wrapping styles to Ethiopic, word-break:break-all may be the right?

**Comment by xfq** [comment]
CSSWG issue closed with an editorial fix: https://github.com/w3c/csswg-drafts/commit/1feb256f0d8f573d3582c612983c524186418f93
