### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by plehegar** [w3c/i18n-activity#847]
**This is a tracker issue.** Only discuss things here if they are i18n group internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/manifest/issues/848

**Comment by xfq** [comment]
WG issue closed as a duplicate of https://github.com/w3c/manifest/issues/676 (our tracker issue is https://github.com/w3c/i18n-activity/issues/914 )
