### ISSUE TITLE
[css-text-3] replaced elements and atomic inlines with non default line-break

### ISSUE THREAD

**Issue by plehegar** [w3c/i18n-activity#859]
**This is a tracker issue.** Only discuss things here if they are i18n group internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/pull/4755

**Comment by himorin** [comment]
short summary: followup PR for https://github.com/w3c/csswg-drafts/issues/4576, make behavior to line-breaking class ID for replaced elements and atomic inlines with non-default line-break value

**Comment by xfq** [comment]
PR closed (without merging) as the resolution in https://github.com/w3c/csswg-drafts/issues/4949#issuecomment-624705207 decided on a different approach.
