### ISSUE TITLE
[css-text-3] Adjust definition of word-break to handle letters with not-yet-existing UAX14 classifications

### ISSUE THREAD

**Issue by plehegar** [w3c/i18n-activity#860]
**This is a tracker issue.** Only discuss things here if they are i18n group internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/4781

**Comment by himorin** [comment]
short summary: make sure CSS specs are drafted in a way that will accommodate future updates to UAX14 on additional categories (e.g. for Javanese)
