### ISSUE TITLE
Bidi considerations in personalization semantics

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#865]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/adapt/issues/155

**Comment by xfq** [comment]
TF issue closed. New spec text: https://w3c.github.io/personalization-semantics/content/#values

**Comment by xfq** [comment]
Since next/previous can be used now, I propose that we close this issue.

**Comment by xfq** [comment]
Closing per yesterday's i18n Teleconference.
