### ISSUE TITLE
[css-ruby] Align ruby with line head or line end

### ISSUE THREAD

**Issue by plehegar** [w3c/i18n-activity#868]
**This is a tracker issue.** Only discuss things here if they are i18n group internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

(duplicate :( )
https://github.com/w3c/csswg-drafts/issues/4857

**Comment by r12a** [comment]
[using this while still closed to discuss a process issue]

@plehegar seems like we need to do one of two things:

a. if creating a new issue, don't raise a tracker issue to go with it - wait 24 hours for the tools to kick in

b. if a tracker issue is created at the same time as  a tracker issue, the tooling should be able to recognise that the tracker issue already exists and not produce a duplicate.

(b) sounds most desirable. What do we need to do to make that work?

cc @xfq @himorin @aphillips

**Comment by plehegar** [comment]
I fixed the tooling this morning. It shouldn't create duplicate anymore.
