### ISSUE TITLE
[css-inline] better name for initial-letters property

### ISSUE THREAD

**Issue by plehegar** [w3c/i18n-activity#870]
**This is a tracker issue.** Only discuss things here if they are i18n group internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/2950

**Comment by xfq** [comment]
CSSWG issue closed as wontfix. The property name is still `initial-letters`.

**Comment by r12a** [comment]
(Actually, it's initial-letter (sing.)) 
+1 to close
