### ISSUE TITLE
data-purpose attribute referencing

### ISSUE THREAD

**Issue by plehegar** [w3c/i18n-activity#874]
**This is a tracker issue.** Only discuss things here if they are i18n group internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/adapt/issues/145

**Comment by xfq** [comment]
TF issue closed with no changes to the spec.

This is somewhat related to the discussions in #779 for HTML and I think it would be useful to make them consistent. Should we close the tracker issue?
