### ISSUE TITLE
[css-ruby] Ruby offset

### ISSUE THREAD

**Issue by plehegar** [w3c/i18n-activity#881]
**This is a tracker issue.** Only discuss things here if they are i18n group internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/4932

**Comment by xfq** [comment]
CSSWG issue closed as wontfix, because offsetting ruby can already be done with margins.

**Comment by r12a** [comment]
+1 to close
