### ISSUE TITLE
[css-ruby] Ruby offset

### ISSUE THREAD

**Issue by plehegar** [w3c/i18n-activity#882]
**This is a tracker issue.** Only discuss things here if they are i18n group internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

https://github.com/w3c/csswg-drafts/issues/4932

Instructions:
- check for the following labels, then remove the PENDING label, then delete these instructions

- TRACKER & S:...  should be there
- add ADVICE-REQUESTED if the WG-issue is specifically asking for i18n to advise/comment
- add NEEDS-ATTENTION if this is an important issue

- if there's an i18n-*lreq label in the WG repo:
   -  ...LREQ label(s) should be there
   - SPEC-TYPE-ISSUE should be there
   - add TYPE-INFO-REQUEST if a request for script/language expert advice
    - add I:...  label(s)

**Comment by xfq** [comment]
Looks like a duplicate of https://github.com/w3c/i18n-activity/issues/881

**Comment by plehegar** [comment]
(duplicate)
