### ISSUE TITLE
Make it clear that scalabilityMode is case-sensitive

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-activity#884]
**This is a tracker issue.** Only discuss things here if they are i18n group internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/webrtc-svc/issues/32

**Comment by r12a** [comment]
There's a proposed edit for this. Is it enough to close this issue?

**Comment by xfq** [comment]
WG issue closed.

PR: https://github.com/w3c/webrtc-svc/pull/33/files
