### ISSUE TITLE
HTTP Content-Language header for language declaration

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#896]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/5031

**Comment by r12a** [comment]
Added a list of problems with http Content-Language use for language declarations, after telecon discussion.

**Comment by xfq** [comment]
CSSWG issue closed. HTTP Content-Language has been removed: https://github.com/w3c/csswg-drafts/commit/0fd0dae933a0c773042467947b08bc1d38dbf674

**Comment by r12a** [comment]
+1 to closing
