### ISSUE TITLE
i18n-ISSUE-316: Line breaking defaults

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#91]
Original email thread: 
http://www.w3.org/Mail/flatten/index?subject=I18N-ISSUE-316&list=www-style

**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/5068

**Comment by r12a** [comment]
check the thread

**Comment by xfq** [comment]
The text is still there. Do we want to re-raise this as a GitHub issue?

(Note that `UAX #14` is already referenced normatively in many places in the spec.)

**Comment by r12a** [comment]
The normative references in the spec are all pointing to line-break classes defined in UAX14 to which a particular behaviour in the spec should be assigned.

There's still no statement in the spec (other than a note which simply says that further information can be found for all scripts in UAX14) that says that **in the absence of** other rules, then the UAX14 line-breaks should be applied as a fallback.  Having this in the spec will promote interoperability in the cases not called out, and will encourage implementers to fully implement UAX14 for the non-controversial cases that are currently outstanding. 

I think we should raise a GH issue to give this visibility.

**Comment by r12a** [comment]
GH issue raised at w3c/csswg-drafts#5068

**Comment by xfq** [comment]
CSSWG issue closed.

Commit: https://github.com/w3c/csswg-drafts/commit/98172553952580fc10cd33d5228896a5a391c06f

i18n WG discussions in teleconference: https://www.w3.org/2020/06/04-i18n-minutes.html#item06
