### ISSUE TITLE
appId rules undefined

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#920]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/miniapp-manifest/issues/7

**Comment by plehegar** [comment]
Issue got transferred to a new repo

**Comment by xfq** [comment]
WG issue closed.

PR: https://github.com/w3c/miniapp-manifest/pull/58/files

Current spec text: https://www.w3.org/TR/miniapp-manifest/#app_id-member

**Comment by aphillips** [comment]
Per [ACTION-1227](https://www.w3.org/International/track/actions/1227), removing close label.
