### ISSUE TITLE
appName needs more work

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#921]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/miniapp/issues/102

**Comment by xfq** [comment]
Related: https://github.com/w3c/miniapp/issues/59

**Comment by xfq** [comment]
Closing per yesterday's i18n Teleconference.
