### ISSUE TITLE
Arabic letters connecting between elements with display: inline

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#94]
**This is a tracker issue.  Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/698

For previous comments, see:

http://www.w3.org/Mail/flatten/index?subject=Arabic+letters+connecting+between+elements+with+display%3A+inline&list=www-style

**Comment by r12a** [comment]
Check new text at https://drafts.csswg.org/css-text-3/#boundary-shaping

**Comment by behnam** [comment]
From https://drafts.csswg.org/css-text-3/#boundary-shaping
> Text shaping should not be broken across inline box boundaries otherwise, if it is reasonable and possible for that case given the limitations of the font technology.

Although it's a good start, but the "if it is **reasonable and possible** for that case given the limitations of the font technology" part apparently makes it a matter of choice again and leaves a lot of room for inconsistency between implementations, and eventually, as a result of the inconsistencies, users not being able to rely on it.

Regarding "joining context" of elements, has it been discussed to allow user to control it for `inline` elements, with options to *isolate* the element regarding joining or *inherit* context from surrounding?

**Comment by r12a** [comment]
@behnam , i think this comment belongs with the actual discussion at CSS issue #698 (see the link above), rather than here, which is just a tracker stub.  Could you move it there, and then i'll delete it from here (with this comment too)?

Fwiw, i added some boilerplate text which will start appearing with new issues in this tracker repo, which encourages folks to write their comments in the right place.

**Comment by behnam** [comment]
Sure, @r12a. Looks like I missed the first line after all.

**Comment by r12a** [comment]
Ok, @behnam let me know when you've copied it to the CSS repo, and i'll then delete this subthread. (And btw i only added the first line a few minutes ago, so no worries there.)

**Comment by behnam** [comment]
Thanks, @r12a. Done: https://github.com/w3c/csswg-drafts/issues/698#issuecomment-297472304

**Comment by r12a** [comment]
Fantasai is currently looking for guidance on this issue. See https://github.com/w3c/csswg-drafts/issues/698#issuecomment-407809833

Any takers?

**Comment by r12a** [comment]
Summary is currently stated in the spec as of https://www.w3.org/TR/2018/WD-css-text-3-20181206/#boundary-shaping. That looks good to me, and answers my original question, so i propose to close.

**Comment by r12a** [comment]
Agreed to close during telecon.
