### ISSUE TITLE
Input profile name generation and normalization rules incomplete

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#953]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/immersive-web/webxr/issues/1121

**Comment by himorin** [comment]
spec fixed by https://github.com/immersive-web/webxr/pull/1122/files with (one of) suggested text.
