### ISSUE TITLE
Having names of users from various cultural backgrounds

### ISSUE THREAD

**Issue by fsasaki** [w3c/i18n-activity#956]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/coga/issues/161

**Comment by xfq** [comment]
Coga TF issue closed.

Names in the old version: Alison, Amy, Anna, Carolyn, Frank, George, Jonathan, Maria, Sam, Tom

Names in the current version: Alison, Amy, George, Gopal, Jonathan, Kwame, Maria, Sam, Tal, Yuki

**Comment by r12a** [comment]
Hmm. 50% is better than none, but still not particularly representative...

**Comment by xfq** [comment]
Closing per https://www.w3.org/2022/06/09-i18n-minutes.html#t06
