### ISSUE TITLE
Provide a reference to language tags as the key means to achieve the goal of unambigous text formatting

### ISSUE THREAD

**Issue by fsasaki** [w3c/i18n-activity#957]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/coga/issues/160

**Comment by xfq** [comment]
Coga TF issue closed.

New spec text: https://w3c.github.io/coga/content-usable/#more-details-14
