### ISSUE TITLE
Control Characters Roll Call on implementation

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#97]
http://www.w3.org/Mail/flatten/index?subject=Control+Characters+Roll+Call+on+implementation&list=www-style
## 

Greg Whitworth   Thu, 10 Sep 2015 20:21:05 +0000

Hello everyone,

As I brought up at recent F2F, and I plan to bring up again at TPAC, we all agreed[1] to implement behind a flag the breaking change stated in CSS Text L3 to render control characters.

```
# Control characters (Unicode category Cc) other than tab (U+0009), line feed (U+000A), and carriage return (U+000D) must be rendered as a visible glyph and
# otherwise treated as any other character of the Other Symbols (So) general category and Common script. The UA may use a glyph provided by a font specifically
# for the control character, substitute the glyphs provided for the corresponding symbol in the Control Pictures block, generate a visual representation of its
# codepoint value, or use some other method to provide an appropriate visible glyph. As required by [UNICODE], unsupported Default_ignorable characters
# must be ignored for rendering.
```

We have implemented this in Microsoft Edge for all C0 and if it did not already have a hex box in the selected font we are using U+25AF (White Vertical Rectangle). One thing of note is that we noticed all browsers throw away the C1 control characters during HTML parsing so this replacement isn't possible. If the other UAs can confirm this we should adjust the language in the text to only change the C0 control characters and ensure that your HTML parser is disposing of the C1 block.

Here are bugs for the dev work in each browser:
Mozilla: http://bugzilla.mozilla.org/show_bug.cgi?id=1099557
Webkit: Can't seem to find one (Dean, can you please get me one)
Blink: Can't find one (Tab, can you please get me one)
Microsoft: Implemented behind a flag, I'll provide an email once it's available in an insider preview

I want to **reiterate** that while this is not a monumental change, this is actually an important practice for all of us to work together on a breaking change and potentially increase this to clean up the web platform in the future.

Please let me know where you development status is and if you expect to have the development done by October (TPAC). Remember, it does not have to ship, just be completed.

From there we can start the PR machines and tooling to let authors know of this breaking change.

Thanks,
Greg

[1] http://logs.csswg.org/irc.w3.org/css/2015-02-08/#e520447

**Comment by r12a** [comment]
Implemented and deployed per Fantasai.

**Comment by KatyMawhood** [comment]
@r12a appears happy with the changes made. I, therefore, propose to close this issue.

**Comment by KatyMawhood** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2019/03/28-i18n-minutes.html).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
&lt;Katy> <a href="https://github.com/w3c/i18n-activity/issues/97">https://github.com/w3c/i18n-activity/issues/97</a><br/>
<b>RESOLUTION:</b> close issue 97<br/>
</details>

**Comment by r12a** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2019/03/28-i18n-minutes.html).

- `RESOLVED:  close issue 97`
<details><summary><i class="differentiate">View the transcript</i></summary>
&lt;Katy> <a href="https://github.com/w3c/i18n-activity/issues/97">https://github.com/w3c/i18n-activity/issues/97</a><br/>
<b>RESOLVED:</b> close issue 97<br/>
</details>
