### ISSUE TITLE
ignoring @charset (editorial nit)

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#978]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/5637

**Comment by xfq** [comment]
CSSWG issue was closed as wontfix.

**Comment by plehegar** [comment]
Please, close this issue since there was agreement reached in the CSS issue
