### ISSUE TITLE
Consider adding/using personal name examples that are more culturally neutral/diverse [editorial]

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#987]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/webauthn/issues/1525

**Comment by xfq** [comment]
Although characters like Alice and Bob may have some special meaning in cryptographic protocols, I don't think it is the case here, and I agree that more diverse names would be better.

**Comment by xfq** [comment]
WG issue closed. Changes: https://github.com/w3c/webauthn/pull/1528/files

**Comment by r12a** [comment]
Closed after checking with Addison.
