### ISSUE TITLE
Support for language/direction metadata in PKCE 'name'?

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#988]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/webauthn/issues/1526

**Comment by xfq** [comment]
We can add a link to the string-meta document.

**Comment by xfq** [comment]
WG issue closed.

PR: https://github.com/w3c/webauthn/pull/1530/files

Spec text: https://w3c.github.io/webauthn/#sctn-strings-langdir

**Comment by r12a** [comment]
Closed after checking with Addison.
