### ISSUE TITLE
String Handling section nits

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#989]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/webauthn/issues/1527

**Comment by xfq** [comment]
(Added `needs-resolution` label.)

**Comment by xfq** [comment]
WG issue closed. Changes: https://github.com/w3c/webauthn/pull/1529/files

**Comment by r12a** [comment]
Closed after checking with Addison.
