### ISSUE TITLE
i18n-ISSUE-491: Change collapse to merge for ruby-merge

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#99]
§ https://github.com/w3c/csswg-drafts/issues/786

formerly was raised as email on 2015-09-23, but no response

http://www.w3.org/Mail/flatten/index?subject=i18n-ISSUE-491&list=www-style

**Comment by xfq** [comment]
CSSWG issue closed. `ruby-merge: collapse` was renamed to `ruby-merge: merge`.

New spec text: https://drafts.csswg.org/css-ruby/#valdef-ruby-merge-merge

**Comment by r12a** [comment]
Closing this in favour of https://github.com/w3c/i18n-activity/issues/894
